import type { Difficulty } from "../types";

export interface SampleTopic {
  name: string;
  minutes: number;
  difficulty: Difficulty;
}

export interface SampleSubject {
  name: string;
  color: string;
  topics: SampleTopic[];
}

/**
 * داده‌ی نمونه‌ی دروس پزشکی — سرفصل کامل منابع اصلی بالینی:
 * جراحی لارنس (Essentials of General Surgery)، زنان بکمن (Beckmann & Ling's Ob/Gyn)،
 * اطفال نلسون (Nelson Textbook of Pediatrics) و بیماری‌های عفونی (Harrison).
 * `minutes` زمان تخمینی مطالعه‌ی هر مبحث به دقیقه است.
 */
export const SAMPLE_SUBJECTS: SampleSubject[] = [
  {
    name: "جراحی (لارنس)",
    color: "#8b5cf6",
    topics: [
      { name: "ارزیابی قبل از عمل و مراقبت از بیمار جراحی", minutes: 120, difficulty: 2 },
      { name: "مایعات، الکترولیت‌ها و تعادل اسید و باز", minutes: 150, difficulty: 3 },
      { name: "تغذیه‌ی جراحی", minutes: 90, difficulty: 2 },
      { name: "خونریزی جراحی و اختلالات انعقادی", minutes: 120, difficulty: 3 },
      { name: "شوک", minutes: 120, difficulty: 3 },
      { name: "مراقبت‌های ویژه‌ی جراحی", minutes: 120, difficulty: 3 },
      { name: "زخم و ترمیم زخم", minutes: 90, difficulty: 2 },
      { name: "عفونت‌های جراحی", minutes: 120, difficulty: 2 },
      { name: "تروما", minutes: 180, difficulty: 3 },
      { name: "سوختگی", minutes: 120, difficulty: 2 },
      { name: "دیواره‌ی شکم و فتق", minutes: 120, difficulty: 2 },
      { name: "مری", minutes: 120, difficulty: 3 },
      { name: "معده و دوازدهه", minutes: 150, difficulty: 3 },
      { name: "روده‌ی باریک و آپاندیس", minutes: 150, difficulty: 2 },
      { name: "کولون، رکتوم و مقعد", minutes: 150, difficulty: 3 },
      { name: "مجاری صفراوی", minutes: 150, difficulty: 3 },
      { name: "پانکراس", minutes: 120, difficulty: 3 },
      { name: "کبد", minutes: 120, difficulty: 3 },
      { name: "پستان", minutes: 120, difficulty: 2 },
      { name: "جراحی غدد درون‌ریز", minutes: 120, difficulty: 3 },
      { name: "طحال و غدد لنفاوی", minutes: 90, difficulty: 2 },
      { name: "بیماری‌های عروقی", minutes: 150, difficulty: 3 },
      { name: "پیوند اعضا", minutes: 90, difficulty: 2 },
      { name: "انکولوژی جراحی", minutes: 120, difficulty: 2 },
      { name: "تکنیک‌ها و مهارت‌های جراحی", minutes: 90, difficulty: 2 },
    ],
  },
  {
    name: "زنان (بکمن)",
    color: "#ec4899",
    topics: [
      { name: "معاینه‌ی سلامت زنان و مدیریت مراقبت", minutes: 90, difficulty: 2 },
      { name: "نقش متخصص زنان در غربالگری و مراقبت پیشگیرانه", minutes: 90, difficulty: 1 },
      { name: "اخلاق، مسئولیت و ایمنی بیمار در زنان", minutes: 60, difficulty: 1 },
      { name: "جنین‌شناسی و آناتومی", minutes: 120, difficulty: 2 },
      { name: "فیزیولوژی مادر و جنین", minutes: 120, difficulty: 2 },
      { name: "مراقبت قبل از بارداری", minutes: 120, difficulty: 2 },
      { name: "ژنتیک و اختلالات ژنتیکی در زنان", minutes: 120, difficulty: 3 },
      { name: "مراقبت حین زایمان", minutes: 150, difficulty: 2 },
      { name: "زایمان غیرطبیعی و پایش جنین", minutes: 150, difficulty: 3 },
      { name: "مراقبت فوری نوزاد", minutes: 90, difficulty: 2 },
      { name: "مراقبت پس از زایمان", minutes: 90, difficulty: 1 },
      { name: "خونریزی پس از زایمان", minutes: 120, difficulty: 3 },
      { name: "حاملگی چندقلویی", minutes: 90, difficulty: 2 },
      { name: "اختلالات رشد جنین (محدودیت رشد و ماکروزومی)", minutes: 120, difficulty: 3 },
      { name: "زایمان زودرس", minutes: 120, difficulty: 3 },
      { name: "خونریزی سه‌ماهه‌ی سوم", minutes: 120, difficulty: 3 },
      { name: "پارگی زودرس پرده‌ها", minutes: 90, difficulty: 2 },
      { name: "بارداری پس از موعد", minutes: 60, difficulty: 1 },
      { name: "حاملگی نابجا و سقط", minutes: 120, difficulty: 3 },
      { name: "اختلالات غدد درون‌ریز در بارداری", minutes: 120, difficulty: 3 },
      { name: "عوارض گوارشی، کلیوی و جراحی در بارداری", minutes: 120, difficulty: 2 },
      { name: "اختلالات قلبی‌عروقی و تنفسی در بارداری", minutes: 120, difficulty: 3 },
      { name: "عوارض خونی و ایمونولوژیک در بارداری", minutes: 120, difficulty: 3 },
      { name: "بیماری‌های عفونی در بارداری", minutes: 120, difficulty: 2 },
      { name: "اختلالات عصبی و روانپزشکی در بارداری", minutes: 90, difficulty: 2 },
      { name: "پیشگیری از بارداری", minutes: 120, difficulty: 2 },
      { name: "عقیم‌سازی", minutes: 60, difficulty: 1 },
      { name: "ولوواژینیت", minutes: 90, difficulty: 2 },
      { name: "عفونت‌های منتقله‌ی جنسی", minutes: 120, difficulty: 2 },
      { name: "افتادگی لگن، بی‌اختیاری ادرار و عفونت ادراری", minutes: 120, difficulty: 2 },
      { name: "اندومتریوز", minutes: 90, difficulty: 2 },
      { name: "دیسمنوره و درد مزمن لگن", minutes: 90, difficulty: 2 },
      { name: "اختلالات پستان", minutes: 120, difficulty: 2 },
      { name: "پروسیجرهای زنان", minutes: 90, difficulty: 1 },
      { name: "جنسیت انسانی", minutes: 60, difficulty: 1 },
      { name: "تجاوز جنسی و خشونت خانگی", minutes: 60, difficulty: 1 },
      { name: "سیکل‌های تولیدمثل", minutes: 90, difficulty: 2 },
      { name: "بلوغ", minutes: 90, difficulty: 2 },
      { name: "آمنوره و خونریزی غیرطبیعی رحم", minutes: 150, difficulty: 3 },
      { name: "هیرسوتیسم و ویریلیزاسیون", minutes: 90, difficulty: 2 },
      { name: "یائسگی", minutes: 90, difficulty: 2 },
      { name: "ناباروری", minutes: 150, difficulty: 3 },
      { name: "سندرم پیش از قاعدگی و اختلال دیسفوریک", minutes: 60, difficulty: 1 },
      { name: "زیست‌شناسی سلولی و اصول درمان سرطان", minutes: 90, difficulty: 2 },
      { name: "نئوپلازی تروفوبلاستیک حاملگی", minutes: 90, difficulty: 3 },
      { name: "بیماری و نئوپلازی ولو و واژن", minutes: 90, difficulty: 2 },
      { name: "نئوپلازی و کارسینوم سرویکس", minutes: 120, difficulty: 3 },
      { name: "لیومیوم و نئوپلازی رحم", minutes: 90, difficulty: 2 },
      { name: "سرطان جسم رحم", minutes: 90, difficulty: 3 },
      { name: "بیماری‌های تخمدان و آدنکس", minutes: 120, difficulty: 3 },
    ],
  },
  {
    name: "اطفال (نلسون)",
    color: "#f59e0b",
    topics: [
      { name: "کلیات طب اطفال", minutes: 60, difficulty: 1 },
      { name: "رشد، تکامل و رفتار", minutes: 150, difficulty: 2 },
      { name: "اختلالات رفتاری و روانپزشکی", minutes: 120, difficulty: 2 },
      { name: "اختلالات یادگیری و تکامل", minutes: 90, difficulty: 2 },
      { name: "تغذیه", minutes: 120, difficulty: 2 },
      { name: "اختلالات مایعات و الکترولیت‌ها", minutes: 150, difficulty: 3 },
      { name: "اورژانس، مراقبت ویژه و بیهوشی", minutes: 150, difficulty: 3 },
      { name: "ژنتیک انسانی", minutes: 90, difficulty: 2 },
      { name: "اختلالات متابولیک", minutes: 120, difficulty: 3 },
      { name: "جنین و نوزاد", minutes: 180, difficulty: 3 },
      { name: "طب نوجوانان", minutes: 90, difficulty: 2 },
      { name: "ایمونولوژی", minutes: 90, difficulty: 2 },
      { name: "اختلالات آلرژیک", minutes: 90, difficulty: 2 },
      { name: "بیماری‌های روماتیسمی کودکان", minutes: 120, difficulty: 3 },
      { name: "بیماری‌های عفونی", minutes: 180, difficulty: 3 },
      { name: "دستگاه گوارش", minutes: 150, difficulty: 2 },
      { name: "دستگاه تنفس", minutes: 150, difficulty: 2 },
      { name: "دستگاه قلب و عروق", minutes: 150, difficulty: 3 },
      { name: "بیماری‌های خون", minutes: 120, difficulty: 2 },
      { name: "سرطان و تومورهای خوش‌خیم", minutes: 120, difficulty: 3 },
      { name: "نفرولوژی", minutes: 120, difficulty: 3 },
      { name: "اختلالات اورولوژی در شیرخواران و کودکان", minutes: 90, difficulty: 2 },
      { name: "مشکلات زنان در دوران کودکی", minutes: 60, difficulty: 1 },
      { name: "دستگاه غدد درون‌ریز", minutes: 120, difficulty: 2 },
      { name: "دستگاه عصبی", minutes: 150, difficulty: 3 },
      { name: "اختلالات عصبی‌عضلانی", minutes: 90, difficulty: 2 },
      { name: "اختلالات چشم", minutes: 60, difficulty: 1 },
      { name: "گوش", minutes: 60, difficulty: 1 },
      { name: "پوست", minutes: 120, difficulty: 2 },
      { name: "اختلالات استخوان و مفاصل", minutes: 90, difficulty: 2 },
      { name: "طب توانبخشی", minutes: 60, difficulty: 1 },
      { name: "سلامت محیطی", minutes: 60, difficulty: 1 },
      { name: "طب آزمایشگاهی", minutes: 60, difficulty: 1 },
    ],
  },
  {
    name: "عفونی",
    color: "#ef4444",
    topics: [
      { name: "تب و هیپرترمی", minutes: 60, difficulty: 1 },
      { name: "تب و راش", minutes: 90, difficulty: 2 },
      { name: "تب با منشأ نامعلوم", minutes: 120, difficulty: 3 },
      { name: "رویکرد به بیمار عفونی بدحال", minutes: 90, difficulty: 2 },
      { name: "بیماری‌های اسهالی حاد عفونی و مسمومیت غذایی", minutes: 120, difficulty: 2 },
      { name: "عفونت‌های منتقله‌ی جنسی", minutes: 120, difficulty: 2 },
      { name: "عفونت‌های پوست، عضلات و بافت نرم", minutes: 90, difficulty: 2 },
      { name: "استئومیلیت", minutes: 90, difficulty: 2 },
      { name: "کلستریدیوم دیفیسیل", minutes: 60, difficulty: 2 },
      { name: "عفونت‌های استافیلوکوکی", minutes: 90, difficulty: 2 },
      { name: "عفونت‌های استرپتوکوکی و پنوموکوکی", minutes: 120, difficulty: 2 },
      { name: "دیفتری", minutes: 60, difficulty: 1 },
      { name: "بوتولیسم", minutes: 60, difficulty: 2 },
      { name: "کزاز", minutes: 60, difficulty: 1 },
      { name: "سالمونلوز", minutes: 90, difficulty: 2 },
      { name: "شیگلوز", minutes: 90, difficulty: 2 },
      { name: "وبا و سایر ویبریوها", minutes: 60, difficulty: 2 },
      { name: "بروسلوز", minutes: 90, difficulty: 2 },
      { name: "تب تیفوئید", minutes: 90, difficulty: 2 },
      { name: "لپتوسپیروز", minutes: 60, difficulty: 2 },
      { name: "تب راجعه", minutes: 60, difficulty: 1 },
      { name: "بورلیوز لایم", minutes: 60, difficulty: 2 },
      { name: "عفونت‌های حاد سیستم عصبی (مننژیت، آنسفالیت، آبسه مغزی)", minutes: 150, difficulty: 3 },
      { name: "عفونت‌های ادراری", minutes: 90, difficulty: 2 },
      { name: "اندوکاردیت عفونی", minutes: 150, difficulty: 3 },
      { name: "پنومونی", minutes: 150, difficulty: 3 },
      { name: "سل", minutes: 150, difficulty: 3 },
      { name: "سپسیس شدید و شوک سپتیک", minutes: 120, difficulty: 3 },
      { name: "آنتی‌بیوتیک‌ها", minutes: 120, difficulty: 2 },
      { name: "عفونت‌های بیمارستانی", minutes: 90, difficulty: 2 },
      { name: "مونونوکلئوز عفونی", minutes: 60, difficulty: 1 },
      { name: "آنفلوانزا", minutes: 90, difficulty: 2 },
      { name: "سرخجه", minutes: 60, difficulty: 1 },
      { name: "سرخک", minutes: 60, difficulty: 1 },
      { name: "عفونت‌های واریسلا زوستر", minutes: 90, difficulty: 2 },
      { name: "هاری", minutes: 60, difficulty: 1 },
      { name: "اوریون", minutes: 60, difficulty: 1 },
      { name: "HIV و ایدز", minutes: 180, difficulty: 3 },
      { name: "هپاتیت ویروسی", minutes: 150, difficulty: 3 },
      { name: "عفونت‌های تنفسی ویروسی شایع", minutes: 90, difficulty: 2 },
      { name: "هرپس سیمپلکس", minutes: 90, difficulty: 2 },
      { name: "آسپرژیلوز", minutes: 60, difficulty: 2 },
      { name: "کاندیدیاز", minutes: 90, difficulty: 2 },
      { name: "آمیبیاز", minutes: 60, difficulty: 2 },
      { name: "مالاریا", minutes: 120, difficulty: 3 },
      { name: "توکسوپلاسموز", minutes: 90, difficulty: 2 },
      { name: "عفونت‌های رودهای تکیاخته‌ای و تریکومونیاز", minutes: 90, difficulty: 2 },
      { name: "عفونت‌های کرمی روده‌ای", minutes: 90, difficulty: 2 },
      { name: "عفونت‌های سستود", minutes: 60, difficulty: 2 },
      { name: "گاستروانتریت ویروسی", minutes: 60, difficulty: 1 },
    ],
  },
  {
    name: "قلب",
    color: "#6366f1",
    topics: [
      { name: "Heart Failure", minutes: 120, difficulty: 3 },
      { name: "Arrhythmia", minutes: 150, difficulty: 3 },
      { name: "ACS", minutes: 90, difficulty: 2 },
    ],
  },
  {
    name: "فارماکولوژی",
    color: "#0ea5a4",
    topics: [
      { name: "Autonomic", minutes: 80, difficulty: 2 },
      { name: "Antibiotics", minutes: 100, difficulty: 2 },
      { name: "CNS Drugs", minutes: 110, difficulty: 3 },
    ],
  },
];
