import type { Difficulty } from "../types";

export interface SampleTopic {
  /** Permanent key: never derive this from the title or the current array position. */
  id: string;
  aliases?: string[];
  name: string;
  minutes: number;
  difficulty: Difficulty;
}

export interface SampleSubject {
  id: string;
  aliases?: string[];
  name: string;
  color: string;
  topics: SampleTopic[];
}

/**
 * سرفصل‌های پیشنهادی برای برنامه‌ریزی مطالعه؛ نه فهرست دقیق یک ویرایش خاص.
 * زمان و حجم‌ها تخمینی‌اند و کاربر می‌تواند همه‌ی آن‌ها را ویرایش کند.
 * شناسه‌ها دائمی‌اند؛ برای موضوع تازه کلید جدید بسازید، کلید قدیمی را تغییر ندهید.
 */
export const SAMPLE_SUBJECTS: SampleSubject[] = [
  {
    id: "surgery-lawrence",
    name: "جراحی (لارنس)",
    color: "#8b5cf6",
    topics: [
      { id: "surgery-lawrence-001", name: "ارزیابی قبل از عمل و مراقبت از بیمار جراحی", minutes: 120, difficulty: 2 },
      { id: "surgery-lawrence-002", name: "مایعات، الکترولیت‌ها و تعادل اسید و باز", minutes: 150, difficulty: 3 },
      { id: "surgery-lawrence-003", name: "تغذیه‌ی جراحی", minutes: 90, difficulty: 2 },
      { id: "surgery-lawrence-004", name: "خونریزی جراحی و اختلالات انعقادی", minutes: 120, difficulty: 3 },
      { id: "surgery-lawrence-005", name: "شوک", minutes: 120, difficulty: 3 },
      { id: "surgery-lawrence-006", name: "مراقبت‌های ویژه‌ی جراحی", minutes: 120, difficulty: 3 },
      { id: "surgery-lawrence-007", name: "زخم و ترمیم زخم", minutes: 90, difficulty: 2 },
      { id: "surgery-lawrence-008", name: "عفونت‌های جراحی", minutes: 120, difficulty: 2 },
      { id: "surgery-lawrence-009", name: "تروما", minutes: 180, difficulty: 3 },
      { id: "surgery-lawrence-010", name: "سوختگی", minutes: 120, difficulty: 2 },
      { id: "surgery-lawrence-011", name: "دیواره‌ی شکم و فتق", minutes: 120, difficulty: 2 },
      { id: "surgery-lawrence-012", name: "مری", minutes: 120, difficulty: 3 },
      { id: "surgery-lawrence-013", name: "معده و دوازدهه", minutes: 150, difficulty: 3 },
      { id: "surgery-lawrence-014", name: "روده‌ی باریک و آپاندیس", minutes: 150, difficulty: 2 },
      { id: "surgery-lawrence-015", name: "کولون، رکتوم و مقعد", minutes: 150, difficulty: 3 },
      { id: "surgery-lawrence-016", name: "مجاری صفراوی", minutes: 150, difficulty: 3 },
      { id: "surgery-lawrence-017", name: "پانکراس", minutes: 120, difficulty: 3 },
      { id: "surgery-lawrence-018", name: "کبد", minutes: 120, difficulty: 3 },
      { id: "surgery-lawrence-019", name: "پستان", minutes: 120, difficulty: 2 },
      { id: "surgery-lawrence-020", name: "جراحی غدد درون‌ریز", minutes: 120, difficulty: 3 },
      { id: "surgery-lawrence-021", name: "طحال و غدد لنفاوی", minutes: 90, difficulty: 2 },
      { id: "surgery-lawrence-022", name: "بیماری‌های عروقی", minutes: 150, difficulty: 3 },
      { id: "surgery-lawrence-023", name: "پیوند اعضا", minutes: 90, difficulty: 2 },
      { id: "surgery-lawrence-024", name: "انکولوژی جراحی", minutes: 120, difficulty: 2 },
      { id: "surgery-lawrence-025", name: "تکنیک‌ها و مهارت‌های جراحی", minutes: 90, difficulty: 2 },
    ],
  },
  {
    id: "gynecology-beckmann",
    name: "زنان (بکمن)",
    color: "#ec4899",
    topics: [
      { id: "gynecology-beckmann-001", name: "معاینه‌ی سلامت زنان و مدیریت مراقبت", minutes: 90, difficulty: 2 },
      { id: "gynecology-beckmann-002", name: "نقش متخصص زنان در غربالگری و مراقبت پیشگیرانه", minutes: 90, difficulty: 1 },
      { id: "gynecology-beckmann-003", name: "اخلاق، مسئولیت و ایمنی بیمار در زنان", minutes: 60, difficulty: 1 },
      { id: "gynecology-beckmann-004", name: "جنین‌شناسی و آناتومی", minutes: 120, difficulty: 2 },
      { id: "gynecology-beckmann-005", name: "فیزیولوژی مادر و جنین", minutes: 120, difficulty: 2 },
      { id: "gynecology-beckmann-006", name: "مراقبت قبل از بارداری", minutes: 120, difficulty: 2 },
      { id: "gynecology-beckmann-007", name: "ژنتیک و اختلالات ژنتیکی در زنان", minutes: 120, difficulty: 3 },
      { id: "gynecology-beckmann-008", name: "مراقبت حین زایمان", minutes: 150, difficulty: 2 },
      { id: "gynecology-beckmann-009", name: "زایمان غیرطبیعی و پایش جنین", minutes: 150, difficulty: 3 },
      { id: "gynecology-beckmann-010", name: "مراقبت فوری نوزاد", minutes: 90, difficulty: 2 },
      { id: "gynecology-beckmann-011", name: "مراقبت پس از زایمان", minutes: 90, difficulty: 1 },
      { id: "gynecology-beckmann-012", name: "خونریزی پس از زایمان", minutes: 120, difficulty: 3 },
      { id: "gynecology-beckmann-013", name: "حاملگی چندقلویی", minutes: 90, difficulty: 2 },
      { id: "gynecology-beckmann-014", name: "اختلالات رشد جنین (محدودیت رشد و ماکروزومی)", minutes: 120, difficulty: 3 },
      { id: "gynecology-beckmann-015", name: "زایمان زودرس", minutes: 120, difficulty: 3 },
      { id: "gynecology-beckmann-016", name: "خونریزی سه‌ماهه‌ی سوم", minutes: 120, difficulty: 3 },
      { id: "gynecology-beckmann-017", name: "پارگی زودرس پرده‌ها", minutes: 90, difficulty: 2 },
      { id: "gynecology-beckmann-018", name: "بارداری پس از موعد", minutes: 60, difficulty: 1 },
      { id: "gynecology-beckmann-019", name: "حاملگی نابجا و سقط", minutes: 120, difficulty: 3 },
      { id: "gynecology-beckmann-020", name: "اختلالات غدد درون‌ریز در بارداری", minutes: 120, difficulty: 3 },
      { id: "gynecology-beckmann-021", name: "عوارض گوارشی، کلیوی و جراحی در بارداری", minutes: 120, difficulty: 2 },
      { id: "gynecology-beckmann-022", name: "اختلالات قلبی‌عروقی و تنفسی در بارداری", minutes: 120, difficulty: 3 },
      { id: "gynecology-beckmann-023", name: "عوارض خونی و ایمونولوژیک در بارداری", minutes: 120, difficulty: 3 },
      { id: "gynecology-beckmann-024", name: "بیماری‌های عفونی در بارداری", minutes: 120, difficulty: 2 },
      { id: "gynecology-beckmann-025", name: "اختلالات عصبی و روانپزشکی در بارداری", minutes: 90, difficulty: 2 },
      { id: "gynecology-beckmann-026", name: "پیشگیری از بارداری", minutes: 120, difficulty: 2 },
      { id: "gynecology-beckmann-027", name: "عقیم‌سازی", minutes: 60, difficulty: 1 },
      { id: "gynecology-beckmann-028", name: "ولوواژینیت", minutes: 90, difficulty: 2 },
      { id: "gynecology-beckmann-029", name: "عفونت‌های منتقله‌ی جنسی", minutes: 120, difficulty: 2 },
      { id: "gynecology-beckmann-030", name: "افتادگی لگن، بی‌اختیاری ادرار و عفونت ادراری", minutes: 120, difficulty: 2 },
      { id: "gynecology-beckmann-031", name: "اندومتریوز", minutes: 90, difficulty: 2 },
      { id: "gynecology-beckmann-032", name: "دیسمنوره و درد مزمن لگن", minutes: 90, difficulty: 2 },
      { id: "gynecology-beckmann-033", name: "اختلالات پستان", minutes: 120, difficulty: 2 },
      { id: "gynecology-beckmann-034", name: "پروسیجرهای زنان", minutes: 90, difficulty: 1 },
      { id: "gynecology-beckmann-035", name: "جنسیت انسانی", minutes: 60, difficulty: 1 },
      { id: "gynecology-beckmann-036", name: "تجاوز جنسی و خشونت خانگی", minutes: 60, difficulty: 1 },
      { id: "gynecology-beckmann-037", name: "سیکل‌های تولیدمثل", minutes: 90, difficulty: 2 },
      { id: "gynecology-beckmann-038", name: "بلوغ", minutes: 90, difficulty: 2 },
      { id: "gynecology-beckmann-039", name: "آمنوره و خونریزی غیرطبیعی رحم", minutes: 150, difficulty: 3 },
      { id: "gynecology-beckmann-040", name: "هیرسوتیسم و ویریلیزاسیون", minutes: 90, difficulty: 2 },
      { id: "gynecology-beckmann-041", name: "یائسگی", minutes: 90, difficulty: 2 },
      { id: "gynecology-beckmann-042", name: "ناباروری", minutes: 150, difficulty: 3 },
      { id: "gynecology-beckmann-043", name: "سندرم پیش از قاعدگی و اختلال دیسفوریک", minutes: 60, difficulty: 1 },
      { id: "gynecology-beckmann-044", name: "زیست‌شناسی سلولی و اصول درمان سرطان", minutes: 90, difficulty: 2 },
      { id: "gynecology-beckmann-045", name: "نئوپلازی تروفوبلاستیک حاملگی", minutes: 90, difficulty: 3 },
      { id: "gynecology-beckmann-046", name: "بیماری و نئوپلازی ولو و واژن", minutes: 90, difficulty: 2 },
      { id: "gynecology-beckmann-047", name: "نئوپلازی و کارسینوم سرویکس", minutes: 120, difficulty: 3 },
      { id: "gynecology-beckmann-048", name: "لیومیوم و نئوپلازی رحم", minutes: 90, difficulty: 2 },
      { id: "gynecology-beckmann-049", name: "سرطان جسم رحم", minutes: 90, difficulty: 3 },
      { id: "gynecology-beckmann-050", name: "بیماری‌های تخمدان و آدنکس", minutes: 120, difficulty: 3 },
    ],
  },
  {
    id: "pediatrics-nelson",
    name: "اطفال (نلسون)",
    color: "#f59e0b",
    topics: [
      { id: "pediatrics-nelson-001", name: "کلیات طب اطفال", minutes: 60, difficulty: 1 },
      { id: "pediatrics-nelson-002", name: "رشد، تکامل و رفتار", minutes: 150, difficulty: 2 },
      { id: "pediatrics-nelson-003", name: "اختلالات رفتاری و روانپزشکی", minutes: 120, difficulty: 2 },
      { id: "pediatrics-nelson-004", name: "اختلالات یادگیری و تکامل", minutes: 90, difficulty: 2 },
      { id: "pediatrics-nelson-005", name: "تغذیه", minutes: 120, difficulty: 2 },
      { id: "pediatrics-nelson-006", name: "اختلالات مایعات و الکترولیت‌ها", minutes: 150, difficulty: 3 },
      { id: "pediatrics-nelson-007", name: "اورژانس، مراقبت ویژه و بیهوشی", minutes: 150, difficulty: 3 },
      { id: "pediatrics-nelson-008", name: "ژنتیک انسانی", minutes: 90, difficulty: 2 },
      { id: "pediatrics-nelson-009", name: "اختلالات متابولیک", minutes: 120, difficulty: 3 },
      { id: "pediatrics-nelson-010", name: "جنین و نوزاد", minutes: 180, difficulty: 3 },
      { id: "pediatrics-nelson-011", name: "طب نوجوانان", minutes: 90, difficulty: 2 },
      { id: "pediatrics-nelson-012", name: "ایمونولوژی", minutes: 90, difficulty: 2 },
      { id: "pediatrics-nelson-013", name: "اختلالات آلرژیک", minutes: 90, difficulty: 2 },
      { id: "pediatrics-nelson-014", name: "بیماری‌های روماتیسمی کودکان", minutes: 120, difficulty: 3 },
      { id: "pediatrics-nelson-015", name: "بیماری‌های عفونی", minutes: 180, difficulty: 3 },
      { id: "pediatrics-nelson-016", name: "دستگاه گوارش", minutes: 150, difficulty: 2 },
      { id: "pediatrics-nelson-017", name: "دستگاه تنفس", minutes: 150, difficulty: 2 },
      { id: "pediatrics-nelson-018", name: "دستگاه قلب و عروق", minutes: 150, difficulty: 3 },
      { id: "pediatrics-nelson-019", name: "بیماری‌های خون", minutes: 120, difficulty: 2 },
      { id: "pediatrics-nelson-020", name: "سرطان و تومورهای خوش‌خیم", minutes: 120, difficulty: 3 },
      { id: "pediatrics-nelson-021", name: "نفرولوژی", minutes: 120, difficulty: 3 },
      { id: "pediatrics-nelson-022", name: "اختلالات اورولوژی در شیرخواران و کودکان", minutes: 90, difficulty: 2 },
      { id: "pediatrics-nelson-023", name: "مشکلات زنان در دوران کودکی", minutes: 60, difficulty: 1 },
      { id: "pediatrics-nelson-024", name: "دستگاه غدد درون‌ریز", minutes: 120, difficulty: 2 },
      { id: "pediatrics-nelson-025", name: "دستگاه عصبی", minutes: 150, difficulty: 3 },
      { id: "pediatrics-nelson-026", name: "اختلالات عصبی‌عضلانی", minutes: 90, difficulty: 2 },
      { id: "pediatrics-nelson-027", name: "اختلالات چشم", minutes: 60, difficulty: 1 },
      { id: "pediatrics-nelson-028", name: "گوش", minutes: 60, difficulty: 1 },
      { id: "pediatrics-nelson-029", name: "پوست", minutes: 120, difficulty: 2 },
      { id: "pediatrics-nelson-030", name: "اختلالات استخوان و مفاصل", minutes: 90, difficulty: 2 },
      { id: "pediatrics-nelson-031", name: "طب توانبخشی", minutes: 60, difficulty: 1 },
      { id: "pediatrics-nelson-032", name: "سلامت محیطی", minutes: 60, difficulty: 1 },
      { id: "pediatrics-nelson-033", name: "طب آزمایشگاهی", minutes: 60, difficulty: 1 },
    ],
  },
  {
    id: "infectious-harrison",
    name: "عفونی",
    color: "#ef4444",
    topics: [
      { id: "infectious-harrison-001", name: "تب و هیپرترمی", minutes: 60, difficulty: 1 },
      { id: "infectious-harrison-002", name: "تب و راش", minutes: 90, difficulty: 2 },
      { id: "infectious-harrison-003", name: "تب با منشأ نامعلوم", minutes: 120, difficulty: 3 },
      { id: "infectious-harrison-004", name: "رویکرد به بیمار عفونی بدحال", minutes: 90, difficulty: 2 },
      { id: "infectious-harrison-005", name: "بیماری‌های اسهالی حاد عفونی و مسمومیت غذایی", minutes: 120, difficulty: 2 },
      { id: "infectious-harrison-006", name: "عفونت‌های منتقله‌ی جنسی", minutes: 120, difficulty: 2 },
      { id: "infectious-harrison-007", name: "عفونت‌های پوست، عضلات و بافت نرم", minutes: 90, difficulty: 2 },
      { id: "infectious-harrison-008", name: "استئومیلیت", minutes: 90, difficulty: 2 },
      { id: "infectious-harrison-009", name: "کلستریدیوم دیفیسیل", minutes: 60, difficulty: 2 },
      { id: "infectious-harrison-010", name: "عفونت‌های استافیلوکوکی", minutes: 90, difficulty: 2 },
      { id: "infectious-harrison-011", name: "عفونت‌های استرپتوکوکی و پنوموکوکی", minutes: 120, difficulty: 2 },
      { id: "infectious-harrison-012", name: "دیفتری", minutes: 60, difficulty: 1 },
      { id: "infectious-harrison-013", name: "بوتولیسم", minutes: 60, difficulty: 2 },
      { id: "infectious-harrison-014", name: "کزاز", minutes: 60, difficulty: 1 },
      { id: "infectious-harrison-015", name: "سالمونلوز", minutes: 90, difficulty: 2 },
      { id: "infectious-harrison-016", name: "شیگلوز", minutes: 90, difficulty: 2 },
      { id: "infectious-harrison-017", name: "وبا و سایر ویبریوها", minutes: 60, difficulty: 2 },
      { id: "infectious-harrison-018", name: "بروسلوز", minutes: 90, difficulty: 2 },
      { id: "infectious-harrison-019", name: "تب تیفوئید", minutes: 90, difficulty: 2 },
      { id: "infectious-harrison-020", name: "لپتوسپیروز", minutes: 60, difficulty: 2 },
      { id: "infectious-harrison-021", name: "تب راجعه", minutes: 60, difficulty: 1 },
      { id: "infectious-harrison-022", name: "بورلیوز لایم", minutes: 60, difficulty: 2 },
      { id: "infectious-harrison-023", name: "عفونت‌های حاد سیستم عصبی (مننژیت، آنسفالیت، آبسه مغزی)", minutes: 150, difficulty: 3 },
      { id: "infectious-harrison-024", name: "عفونت‌های ادراری", minutes: 90, difficulty: 2 },
      { id: "infectious-harrison-025", name: "اندوکاردیت عفونی", minutes: 150, difficulty: 3 },
      { id: "infectious-harrison-026", name: "پنومونی", minutes: 150, difficulty: 3 },
      { id: "infectious-harrison-027", name: "سل", minutes: 150, difficulty: 3 },
      { id: "infectious-harrison-028", name: "سپسیس شدید و شوک سپتیک", minutes: 120, difficulty: 3 },
      { id: "infectious-harrison-029", name: "آنتی‌بیوتیک‌ها", minutes: 120, difficulty: 2 },
      { id: "infectious-harrison-030", name: "عفونت‌های بیمارستانی", minutes: 90, difficulty: 2 },
      { id: "infectious-harrison-031", name: "مونونوکلئوز عفونی", minutes: 60, difficulty: 1 },
      { id: "infectious-harrison-032", name: "آنفلوانزا", minutes: 90, difficulty: 2 },
      { id: "infectious-harrison-033", name: "سرخجه", minutes: 60, difficulty: 1 },
      { id: "infectious-harrison-034", name: "سرخک", minutes: 60, difficulty: 1 },
      { id: "infectious-harrison-035", name: "عفونت‌های واریسلا زوستر", minutes: 90, difficulty: 2 },
      { id: "infectious-harrison-036", name: "هاری", minutes: 60, difficulty: 1 },
      { id: "infectious-harrison-037", name: "اوریون", minutes: 60, difficulty: 1 },
      { id: "infectious-harrison-038", name: "HIV و ایدز", minutes: 180, difficulty: 3 },
      { id: "infectious-harrison-039", name: "هپاتیت ویروسی", minutes: 150, difficulty: 3 },
      { id: "infectious-harrison-040", name: "عفونت‌های تنفسی ویروسی شایع", minutes: 90, difficulty: 2 },
      { id: "infectious-harrison-041", name: "هرپس سیمپلکس", minutes: 90, difficulty: 2 },
      { id: "infectious-harrison-042", name: "آسپرژیلوز", minutes: 60, difficulty: 2 },
      { id: "infectious-harrison-043", name: "کاندیدیاز", minutes: 90, difficulty: 2 },
      { id: "infectious-harrison-044", name: "آمیبیاز", minutes: 60, difficulty: 2 },
      { id: "infectious-harrison-045", name: "مالاریا", minutes: 120, difficulty: 3 },
      { id: "infectious-harrison-046", name: "توکسوپلاسموز", minutes: 90, difficulty: 2 },
      { id: "infectious-harrison-047", name: "عفونت‌های رودهای تکیاخته‌ای و تریکومونیاز", minutes: 90, difficulty: 2 },
      { id: "infectious-harrison-048", name: "عفونت‌های کرمی روده‌ای", minutes: 90, difficulty: 2 },
      { id: "infectious-harrison-049", name: "عفونت‌های سستود", minutes: 60, difficulty: 2 },
      { id: "infectious-harrison-050", name: "گاستروانتریت ویروسی", minutes: 60, difficulty: 1 },
    ],
  },
  {
    id: "cardiology-harrison",
    name: "قلب (هاریسون)",
    aliases: ["قلب"],
    color: "#6366f1",
    topics: [
      { id: "cardiology-harrison-001", name: "نارسایی قلب", aliases: ["Heart Failure"], minutes: 120, difficulty: 3 },
      { id: "cardiology-harrison-002", name: "آریتمی‌ها", aliases: ["Arrhythmia"], minutes: 150, difficulty: 3 },
      { id: "cardiology-harrison-003", name: "سندرم کرونری حاد (ACS)", aliases: ["ACS"], minutes: 90, difficulty: 2 },
      { id: "cardiology-harrison-004", name: "رویکرد به بیمار قلبی و معاینه قلب", minutes: 90, difficulty: 2 },
      { id: "cardiology-harrison-005", name: "الکتروکاردیوگرافی و روش‌های تشخیصی قلب", minutes: 150, difficulty: 3 },
      { id: "cardiology-harrison-006", name: "بیماری ایسکمیک پایدار قلب", minutes: 120, difficulty: 2 },
      { id: "cardiology-harrison-007", name: "فیبریلاسیون و فلوتر دهلیزی", minutes: 120, difficulty: 3 },
      { id: "cardiology-harrison-008", name: "برادی‌آریتمی‌ها و اختلالات هدایت", minutes: 120, difficulty: 3 },
      { id: "cardiology-harrison-009", name: "تاکی‌کاردی بطنی و مرگ ناگهانی قلبی", minutes: 120, difficulty: 3 },
      { id: "cardiology-harrison-010", name: "کاردیومیوپاتی‌ها و میوکاردیت", minutes: 120, difficulty: 3 },
      { id: "cardiology-harrison-011", name: "بیماری‌های دریچه‌ای قلب", minutes: 150, difficulty: 3 },
      { id: "cardiology-harrison-012", name: "بیماری‌های پریکارد", minutes: 90, difficulty: 2 },
      { id: "cardiology-harrison-013", name: "بیماری‌های مادرزادی قلب در بزرگسالان", minutes: 120, difficulty: 3 },
      { id: "cardiology-harrison-014", name: "پرفشاری خون سیستمیک", minutes: 120, difficulty: 2 },
      { id: "cardiology-harrison-015", name: "بیماری‌های آئورت و عروق محیطی", minutes: 120, difficulty: 3 },
      { id: "cardiology-harrison-016", name: "شوک کاردیوژنیک و ادم ریوی", minutes: 90, difficulty: 3 },
      { id: "cardiology-harrison-017", name: "اختلالات چربی و پیشگیری قلبی‌عروقی", minutes: 90, difficulty: 2 },
      { id: "cardiology-harrison-018", name: "اندوکاردیت و تب روماتیسمی", minutes: 120, difficulty: 3 },
    ],
  },
  {
    id: "pharmacology",
    name: "فارماکولوژی",
    color: "#0ea5a4",
    topics: [
      { id: "pharmacology-001", name: "Autonomic", minutes: 80, difficulty: 2 },
      { id: "pharmacology-002", name: "Antibiotics", minutes: 100, difficulty: 2 },
      { id: "pharmacology-003", name: "CNS Drugs", minutes: 110, difficulty: 3 },
    ],
  },
  {
    id: "endocrinology-harrison",
    name: "غدد (هاریسون)",
    color: "#f97316",
    topics: [
      { id: "endocrinology-harrison-001", name: "رویکرد به اختلالات غدد درون‌ریز", minutes: 90, difficulty: 2 },
      { id: "endocrinology-harrison-002", name: "هیپوفیز قدامی و توده‌های ناحیه سلا", minutes: 120, difficulty: 3 },
      { id: "endocrinology-harrison-003", name: "اختلالات رشد و آکرومگالی", minutes: 90, difficulty: 2 },
      { id: "endocrinology-harrison-004", name: "دیابت بی‌مزه و اختلالات وازوپرسین", minutes: 90, difficulty: 3 },
      { id: "endocrinology-harrison-005", name: "رویکرد به بیماری‌های تیروئید", minutes: 90, difficulty: 2 },
      { id: "endocrinology-harrison-006", name: "کم‌کاری و پرکاری تیروئید", minutes: 150, difficulty: 3 },
      { id: "endocrinology-harrison-007", name: "ندول‌ها و سرطان تیروئید", minutes: 120, difficulty: 3 },
      { id: "endocrinology-harrison-008", name: "بیماری‌های قشر آدرنال", minutes: 150, difficulty: 3 },
      { id: "endocrinology-harrison-009", name: "فئوکروموسیتوم و بیماری‌های مدولای آدرنال", minutes: 90, difficulty: 3 },
      { id: "endocrinology-harrison-010", name: "دیابت ملیتوس؛ تشخیص و درمان", minutes: 180, difficulty: 3 },
      { id: "endocrinology-harrison-011", name: "عوارض حاد و مزمن دیابت", minutes: 150, difficulty: 3 },
      { id: "endocrinology-harrison-012", name: "هیپوگلیسمی", minutes: 90, difficulty: 2 },
      { id: "endocrinology-harrison-013", name: "اختلالات کلسیم و پاراتیروئید", minutes: 120, difficulty: 3 },
      { id: "endocrinology-harrison-014", name: "پوکی استخوان و بیماری‌های متابولیک استخوان", minutes: 120, difficulty: 2 },
      { id: "endocrinology-harrison-015", name: "چاقی و سندرم متابولیک", minutes: 90, difficulty: 2 },
      { id: "endocrinology-harrison-016", name: "اختلالات غدد تولیدمثل", minutes: 120, difficulty: 3 },
    ],
  },
  {
    id: "nephrology-harrison",
    name: "کلیه (هاریسون)",
    color: "#0ea5e9",
    topics: [
      { id: "nephrology-harrison-001", name: "رویکرد به بیمار کلیوی و آزمایش ادرار", minutes: 90, difficulty: 2 },
      { id: "nephrology-harrison-002", name: "اختلالات سدیم و تعادل آب", minutes: 120, difficulty: 3 },
      { id: "nephrology-harrison-003", name: "اختلالات پتاسیم", minutes: 90, difficulty: 3 },
      { id: "nephrology-harrison-004", name: "اختلالات اسید و باز", minutes: 150, difficulty: 3 },
      { id: "nephrology-harrison-005", name: "آسیب حاد کلیه", minutes: 150, difficulty: 3 },
      { id: "nephrology-harrison-006", name: "بیماری مزمن کلیه", minutes: 150, difficulty: 3 },
      { id: "nephrology-harrison-007", name: "دیالیز و پیوند کلیه", minutes: 120, difficulty: 3 },
      { id: "nephrology-harrison-008", name: "سندرم نفریتیک و گلومرولونفریت‌ها", minutes: 150, difficulty: 3 },
      { id: "nephrology-harrison-009", name: "سندرم نفروتیک", minutes: 120, difficulty: 3 },
      { id: "nephrology-harrison-010", name: "نفروپاتی دیابتی و بیماری‌های سیستمیک کلیه", minutes: 120, difficulty: 3 },
      { id: "nephrology-harrison-011", name: "بیماری‌های توبولی و بینابینی کلیه", minutes: 120, difficulty: 3 },
      { id: "nephrology-harrison-012", name: "بیماری‌های عروقی کلیه", minutes: 90, difficulty: 3 },
      { id: "nephrology-harrison-013", name: "بیماری‌های کیستیک و ارثی کلیه", minutes: 90, difficulty: 2 },
      { id: "nephrology-harrison-014", name: "سنگ‌های ادراری و نفروکلسی‌نوز", minutes: 90, difficulty: 2 },
      { id: "nephrology-harrison-015", name: "انسداد مجاری ادراری", minutes: 90, difficulty: 2 },
      { id: "nephrology-harrison-016", name: "عفونت ادراری و پیلونفریت", minutes: 90, difficulty: 2 },
    ],
  },
  {
    id: "rheumatology-harrison",
    name: "روماتولوژی (هاریسون)",
    color: "#8b5cf6",
    topics: [
      { id: "rheumatology-harrison-001", name: "رویکرد به درد مفصل و بیماری‌های روماتیسمی", minutes: 90, difficulty: 2 },
      { id: "rheumatology-harrison-002", name: "آزمایش‌های ایمنی و اتوآنتی‌بادی‌ها", minutes: 90, difficulty: 2 },
      { id: "rheumatology-harrison-003", name: "آرتریت روماتوئید", minutes: 150, difficulty: 3 },
      { id: "rheumatology-harrison-004", name: "لوپوس اریتماتوی سیستمیک", minutes: 150, difficulty: 3 },
      { id: "rheumatology-harrison-005", name: "سندرم آنتی‌فسفولیپید", minutes: 90, difficulty: 3 },
      { id: "rheumatology-harrison-006", name: "اسکلروز سیستمیک", minutes: 120, difficulty: 3 },
      { id: "rheumatology-harrison-007", name: "میوپاتی‌های التهابی", minutes: 90, difficulty: 3 },
      { id: "rheumatology-harrison-008", name: "سندرم شوگرن", minutes: 90, difficulty: 2 },
      { id: "rheumatology-harrison-009", name: "واسکولیت‌ها", minutes: 180, difficulty: 3 },
      { id: "rheumatology-harrison-010", name: "اسپوندیلوآرتریت‌ها", minutes: 120, difficulty: 3 },
      { id: "rheumatology-harrison-011", name: "نقرس و آرتریت‌های ناشی از کریستال", minutes: 120, difficulty: 2 },
      { id: "rheumatology-harrison-012", name: "استئوآرتریت", minutes: 90, difficulty: 2 },
      { id: "rheumatology-harrison-013", name: "آرتریت عفونی", minutes: 90, difficulty: 3 },
      { id: "rheumatology-harrison-014", name: "فیبرومیالژیا و اختلالات بافت نرم", minutes: 90, difficulty: 2 },
      { id: "rheumatology-harrison-015", name: "بیماری بهجت و بیماری‌های خودالتهابی", minutes: 120, difficulty: 3 },
      { id: "rheumatology-harrison-016", name: "سارکوئیدوز و آمیلوئیدوز", minutes: 120, difficulty: 3 },
    ],
  },
  {
    id: "hematology-harrison",
    name: "خون (هاریسون)",
    color: "#e11d48",
    topics: [
      { id: "hematology-harrison-001", name: "رویکرد به کم‌خونی و تفسیر شمارش سلول‌های خون", minutes: 120, difficulty: 2 },
      { id: "hematology-harrison-002", name: "کم‌خونی فقر آهن و کم‌خونی بیماری مزمن", minutes: 120, difficulty: 2 },
      { id: "hematology-harrison-003", name: "کم‌خونی مگالوبلاستیک", minutes: 90, difficulty: 2 },
      { id: "hematology-harrison-004", name: "کم‌خونی‌های همولیتیک", minutes: 120, difficulty: 3 },
      { id: "hematology-harrison-005", name: "هموگلوبینوپاتی‌ها و تالاسمی", minutes: 120, difficulty: 3 },
      { id: "hematology-harrison-006", name: "کم‌خونی آپلاستیک و نارسایی مغز استخوان", minutes: 90, difficulty: 3 },
      { id: "hematology-harrison-007", name: "اختلالات گرانولوسیت‌ها", minutes: 90, difficulty: 2 },
      { id: "hematology-harrison-008", name: "لوسمی‌های حاد", minutes: 150, difficulty: 3 },
      { id: "hematology-harrison-009", name: "لوسمی‌های مزمن", minutes: 120, difficulty: 3 },
      { id: "hematology-harrison-010", name: "لنفوم هوچکین و غیرهوچکین", minutes: 150, difficulty: 3 },
      { id: "hematology-harrison-011", name: "مولتیپل میلوما و اختلالات پلاسماسل", minutes: 120, difficulty: 3 },
      { id: "hematology-harrison-012", name: "نئوپلاسم‌های میلوپرولیفراتیو", minutes: 120, difficulty: 3 },
      { id: "hematology-harrison-013", name: "سندرم‌های میلودیسپلاستیک", minutes: 90, difficulty: 3 },
      { id: "hematology-harrison-014", name: "اختلالات پلاکت و ترومبوسیتوپنی", minutes: 120, difficulty: 3 },
      { id: "hematology-harrison-015", name: "اختلالات انعقاد و خونریزی", minutes: 150, difficulty: 3 },
      { id: "hematology-harrison-016", name: "ترومبوز و درمان ضدانعقادی", minutes: 120, difficulty: 3 },
      { id: "hematology-harrison-017", name: "طب انتقال خون", minutes: 90, difficulty: 2 },
      { id: "hematology-harrison-018", name: "پیوند سلول‌های بنیادی خون‌ساز", minutes: 90, difficulty: 3 },
    ],
  },
  {
    id: "gastroenterology-harrison",
    name: "گوارش (هاریسون)",
    color: "#d97706",
    topics: [
      { id: "gastroenterology-harrison-001", name: "رویکرد به علائم گوارشی و روش‌های تشخیصی", minutes: 90, difficulty: 2 },
      { id: "gastroenterology-harrison-002", name: "بیماری‌های مری و رفلاکس", minutes: 120, difficulty: 2 },
      { id: "gastroenterology-harrison-003", name: "زخم پپتیک و هلیکوباکتر پیلوری", minutes: 120, difficulty: 2 },
      { id: "gastroenterology-harrison-004", name: "خونریزی گوارشی", minutes: 150, difficulty: 3 },
      { id: "gastroenterology-harrison-005", name: "اسهال، سوءجذب و بیماری سلیاک", minutes: 150, difficulty: 3 },
      { id: "gastroenterology-harrison-006", name: "بیماری التهابی روده", minutes: 150, difficulty: 3 },
      { id: "gastroenterology-harrison-007", name: "سندرم روده تحریک‌پذیر و اختلالات عملکردی", minutes: 90, difficulty: 2 },
      { id: "gastroenterology-harrison-008", name: "بیماری‌های کولون و رکتوم", minutes: 120, difficulty: 2 },
      { id: "gastroenterology-harrison-009", name: "تومورهای دستگاه گوارش", minutes: 150, difficulty: 3 },
      { id: "gastroenterology-harrison-010", name: "رویکرد به بیماری کبد و تفسیر آزمایش‌های کبدی", minutes: 120, difficulty: 2 },
      { id: "gastroenterology-harrison-011", name: "هپاتیت‌های ویروسی", minutes: 150, difficulty: 3 },
      { id: "gastroenterology-harrison-012", name: "بیماری کبد چرب و کبد الکلی", minutes: 120, difficulty: 2 },
      { id: "gastroenterology-harrison-013", name: "بیماری‌های خودایمنی و متابولیک کبد", minutes: 120, difficulty: 3 },
      { id: "gastroenterology-harrison-014", name: "سیروز و عوارض پرفشاری پورت", minutes: 180, difficulty: 3 },
      { id: "gastroenterology-harrison-015", name: "نارسایی حاد کبد و پیوند کبد", minutes: 120, difficulty: 3 },
      { id: "gastroenterology-harrison-016", name: "بیماری‌های کیسه صفرا و مجاری صفراوی", minutes: 120, difficulty: 2 },
      { id: "gastroenterology-harrison-017", name: "پانکراتیت حاد و مزمن", minutes: 150, difficulty: 3 },
      { id: "gastroenterology-harrison-018", name: "تومورهای کبد، مجاری صفراوی و پانکراس", minutes: 120, difficulty: 3 },
    ],
  },
  {
    id: "pulmonology-harrison",
    name: "ریه (هاریسون)",
    color: "#14b8a6",
    topics: [
      { id: "pulmonology-harrison-001", name: "رویکرد به بیمار تنفسی و تست‌های عملکرد ریه", minutes: 120, difficulty: 2 },
      { id: "pulmonology-harrison-002", name: "آسم", minutes: 120, difficulty: 2 },
      { id: "pulmonology-harrison-003", name: "بیماری انسدادی مزمن ریه (COPD)", minutes: 120, difficulty: 3 },
      { id: "pulmonology-harrison-004", name: "برونشکتازی و فیبروز کیستیک", minutes: 90, difficulty: 2 },
      { id: "pulmonology-harrison-005", name: "پنومونی و آبسه ریه", minutes: 150, difficulty: 3 },
      { id: "pulmonology-harrison-006", name: "سل ریوی", minutes: 120, difficulty: 3 },
      { id: "pulmonology-harrison-007", name: "بیماری‌های بینابینی ریه", minutes: 150, difficulty: 3 },
      { id: "pulmonology-harrison-008", name: "بیماری‌های شغلی و محیطی ریه", minutes: 90, difficulty: 2 },
      { id: "pulmonology-harrison-009", name: "آمبولی ریه و ترومبوآمبولی وریدی", minutes: 150, difficulty: 3 },
      { id: "pulmonology-harrison-010", name: "پرفشاری خون ریوی", minutes: 120, difficulty: 3 },
      { id: "pulmonology-harrison-011", name: "بیماری‌های پلور و پنوموتوراکس", minutes: 120, difficulty: 2 },
      { id: "pulmonology-harrison-012", name: "بیماری‌های مدیاستن", minutes: 90, difficulty: 2 },
      { id: "pulmonology-harrison-013", name: "سرطان ریه", minutes: 150, difficulty: 3 },
      { id: "pulmonology-harrison-014", name: "اختلالات تنفسی حین خواب", minutes: 90, difficulty: 2 },
      { id: "pulmonology-harrison-015", name: "نارسایی تنفسی و سندرم دیسترس تنفسی حاد", minutes: 150, difficulty: 3 },
      { id: "pulmonology-harrison-016", name: "تهویه مکانیکی و اصول مراقبت تنفسی", minutes: 120, difficulty: 3 },
    ],
  },
  {
    id: "radiology-herring",
    name: "رادیولوژی (هرینگ)",
    color: "#3b82f6",
    topics: [
      { id: "radiology-herring-001", name: "اصول تصویربرداری و انتخاب روش مناسب", minutes: 90, difficulty: 1 },
      { id: "radiology-herring-002", name: "ایمنی پرتو و مواد حاجب", minutes: 60, difficulty: 1 },
      { id: "radiology-herring-003", name: "آناتومی طبیعی و رویکرد به رادیوگرافی قفسه سینه", minutes: 120, difficulty: 2 },
      { id: "radiology-herring-004", name: "بیماری‌های فضای هوایی و آتلکتازی", minutes: 120, difficulty: 2 },
      { id: "radiology-herring-005", name: "افیوژن پلور و پنوموتوراکس در تصویربرداری", minutes: 90, difficulty: 2 },
      { id: "radiology-herring-006", name: "قلب و عروق در رادیوگرافی قفسه سینه", minutes: 90, difficulty: 2 },
      { id: "radiology-herring-007", name: "ندول‌ها و توده‌های ریه و مدیاستن", minutes: 120, difficulty: 3 },
      { id: "radiology-herring-008", name: "ابزارها، لوله‌ها و کاتترها در تصاویر", minutes: 90, difficulty: 2 },
      { id: "radiology-herring-009", name: "اصول تصویربرداری شکم و لگن", minutes: 90, difficulty: 2 },
      { id: "radiology-herring-010", name: "انسداد روده و هوای آزاد شکمی", minutes: 120, difficulty: 3 },
      { id: "radiology-herring-011", name: "تصویربرداری کبد، صفرا و پانکراس", minutes: 120, difficulty: 2 },
      { id: "radiology-herring-012", name: "تصویربرداری دستگاه ادراری", minutes: 90, difficulty: 2 },
      { id: "radiology-herring-013", name: "شکستگی‌ها و دررفتگی‌ها", minutes: 150, difficulty: 3 },
      { id: "radiology-herring-014", name: "بیماری‌های مفاصل و ضایعات استخوانی", minutes: 120, difficulty: 2 },
      { id: "radiology-herring-015", name: "تصویربرداری مغز؛ خونریزی و سکته", minutes: 150, difficulty: 3 },
      { id: "radiology-herring-016", name: "تصویربرداری ستون فقرات", minutes: 90, difficulty: 2 },
      { id: "radiology-herring-017", name: "اصول سونوگرافی، سی‌تی و ام‌آر‌آی", minutes: 120, difficulty: 2 },
      { id: "radiology-herring-018", name: "مرور تصویربرداری اورژانس و تروما", minutes: 120, difficulty: 3 },
    ],
  },
  // ── منابع جدید آزمون پره انترنی ۱۴۰۵–۱۴۰۶ ──────────────────────────
  {
    id: "internal-cecil",
    name: "داخلی (سیسیل)",
    color: "#0891b2",
    topics: [
      { id: "internal-cecil-001", name: "سلامت و بیماری ریه", minutes: 120, difficulty: 2 },
      { id: "internal-cecil-002", name: "رویکرد به بیمار تنفسی", minutes: 120, difficulty: 2 },
      { id: "internal-cecil-003", name: "ارزیابی ساختار و عملکرد ریه", minutes: 90, difficulty: 2 },
      { id: "internal-cecil-004", name: "بیماری‌های بینابینی ریه", minutes: 150, difficulty: 3 },
      { id: "internal-cecil-005", name: "بیماری عروقی ریه", minutes: 120, difficulty: 3 },
      { id: "internal-cecil-006", name: "اختلالات پلور، مدیاستن و دیواره قفسه سینه", minutes: 120, difficulty: 2 },
      { id: "internal-cecil-007", name: "نارسایی تنفسی", minutes: 150, difficulty: 3 },
      { id: "internal-cecil-008", name: "ساختار و عملکرد کلیه", minutes: 120, difficulty: 2 },
      { id: "internal-cecil-009", name: "رویکرد به بیمار کلیوی", minutes: 120, difficulty: 2 },
      { id: "internal-cecil-010", name: "بیماری‌های گلومرولی", minutes: 150, difficulty: 3 },
      { id: "internal-cecil-011", name: "اختلالات غیرگلومرولی کلیه", minutes: 120, difficulty: 2 },
      { id: "internal-cecil-012", name: "اختلالات عروقی کلیه", minutes: 120, difficulty: 3 },
      { id: "internal-cecil-013", name: "تظاهرات بالینی گوارشی: درد شکم", minutes: 120, difficulty: 2 },
      { id: "internal-cecil-014", name: "تظاهرات بالینی گوارشی: سوءجذب", minutes: 120, difficulty: 2 },
      { id: "internal-cecil-015", name: "اختلالات مری", minutes: 120, difficulty: 2 },
      { id: "internal-cecil-016", name: "بیماری التهابی روده", minutes: 150, difficulty: 3 },
      { id: "internal-cecil-017", name: "بیماری‌های پانکراس", minutes: 120, difficulty: 3 },
      { id: "internal-cecil-018", name: "نارسایی حاد کبد", minutes: 120, difficulty: 3 },
      { id: "internal-cecil-019", name: "سیروز و عوارض آن", minutes: 150, difficulty: 3 },
      { id: "internal-cecil-020", name: "اختلالات کیسه صفرا و مجاری صفراوی", minutes: 120, difficulty: 2 },
      { id: "internal-cecil-021", name: "اختلالات گرانولوسیت‌ها و مونوسیت‌ها", minutes: 120, difficulty: 2 },
      { id: "internal-cecil-022", name: "اختلالات لنفوسیت‌ها", minutes: 120, difficulty: 3 },
      { id: "internal-cecil-023", name: "هموستاز طبیعی", minutes: 120, difficulty: 2 },
      { id: "internal-cecil-024", name: "اختلالات انعقادی: خونریزی", minutes: 150, difficulty: 3 },
      { id: "internal-cecil-025", name: "اختلالات انعقادی: ترومبوز", minutes: 150, difficulty: 3 },
      { id: "internal-cecil-026", name: "بیولوژی سرطان", minutes: 120, difficulty: 2 },
      { id: "internal-cecil-027", name: "اپیدمیولوژی سرطان", minutes: 90, difficulty: 2 },
      { id: "internal-cecil-028", name: "اصول درمان سرطان", minutes: 120, difficulty: 3 },
      { id: "internal-cecil-029", name: "سرطان‌های گوارشی", minutes: 150, difficulty: 3 },
      { id: "internal-cecil-030", name: "سرطان ریه", minutes: 120, difficulty: 3 },
      { id: "internal-cecil-031", name: "محور هیپوتالاموس-هیپوفیز", minutes: 150, difficulty: 3 },
      { id: "internal-cecil-032", name: "غده فوق کلیوی", minutes: 150, difficulty: 3 },
      { id: "internal-cecil-033", name: "غدد درون‌ریز تولیدمثلی مرد", minutes: 120, difficulty: 2 },
      { id: "internal-cecil-034", name: "چاقی", minutes: 90, difficulty: 2 },
      { id: "internal-cecil-035", name: "اختلالات متابولیسم لیپید", minutes: 120, difficulty: 3 },
      { id: "internal-cecil-036", name: "بیماری‌های استخوان و متابولیسم کلسیم", minutes: 150, difficulty: 2 },
      { id: "internal-cecil-037", name: "پوکی استخوان", minutes: 90, difficulty: 2 },
      { id: "internal-cecil-038", name: "آرتریت روماتوئید", minutes: 150, difficulty: 3 },
      { id: "internal-cecil-039", name: "اسپوندیلوآرتریت‌ها", minutes: 120, difficulty: 3 },
      { id: "internal-cecil-040", name: "لوپوس اریتماتوی سیستمیک", minutes: 150, difficulty: 3 },
      { id: "internal-cecil-041", name: "اسکلروز سیستمیک", minutes: 120, difficulty: 3 },
      { id: "internal-cecil-042", name: "واسکولیت‌های سیستمیک", minutes: 150, difficulty: 3 },
      { id: "internal-cecil-043", name: "آتروپاتی‌های کریستالی", minutes: 120, difficulty: 2 },
      { id: "internal-cecil-044", name: "مراقبت قبل و بعد از عمل", minutes: 120, difficulty: 2 },
      { id: "internal-cecil-045", name: "بیمار سالمند", minutes: 90, difficulty: 2 },
      { id: "internal-cecil-046", name: "مراقبت تسکینی", minutes: 90, difficulty: 1 },
      { id: "internal-cecil-047", name: "الکل و سوءمصرف مواد", minutes: 120, difficulty: 2 },
    ],
  },
  {
    id: "neurology-aminoff",
    name: "مغز و اعصاب (آمینوف)",
    color: "#7c3aed",
    topics: [
      { id: "neurology-aminoff-001", name: "بررسی بیمار مغز و اعصاب", minutes: 120, difficulty: 2 },
      { id: "neurology-aminoff-002", name: "اختلالات هوشیاری و خواب", minutes: 150, difficulty: 3 },
      { id: "neurology-aminoff-003", name: "سردرد و درد صورت", minutes: 120, difficulty: 2 },
      { id: "neurology-aminoff-004", name: "تشنج و صرع", minutes: 150, difficulty: 3 },
      { id: "neurology-aminoff-005", name: "اختلالات حرکتی و فلج", minutes: 150, difficulty: 3 },
      { id: "neurology-aminoff-006", name: "اختلالات مخچه و تعادل", minutes: 120, difficulty: 2 },
      { id: "neurology-aminoff-007", name: "اختلالات بینایی و چشمی-حرکتی", minutes: 120, difficulty: 2 },
      { id: "neurology-aminoff-008", name: "اختلالات حسی", minutes: 120, difficulty: 2 },
      { id: "neurology-aminoff-009", name: "بیماری‌های عروق مغزی (سکته)", minutes: 180, difficulty: 3 },
      { id: "neurology-aminoff-010", name: "خونریزی داخل جمجمه‌ای", minutes: 150, difficulty: 3 },
      { id: "neurology-aminoff-011", name: "تومورهای سیستم عصبی", minutes: 150, difficulty: 3 },
      { id: "neurology-aminoff-012", name: "ضربه مغزی و نخاعی", minutes: 150, difficulty: 3 },
      { id: "neurology-aminoff-013", name: "بیماری‌های دژنراتیو: آلزایمر و پارکینسون", minutes: 150, difficulty: 3 },
      { id: "neurology-aminoff-014", name: "بیماری‌های دمی‌لینه‌کننده (MS)", minutes: 150, difficulty: 3 },
      { id: "neurology-aminoff-015", name: "نوروپاتی‌های محیطی", minutes: 120, difficulty: 2 },
      { id: "neurology-aminoff-016", name: "اختلالات عضلانی و میوپاتی", minutes: 120, difficulty: 2 },
      { id: "neurology-aminoff-017", name: "اختلالات اتصال عصبی-عضلانی", minutes: 120, difficulty: 3 },
      { id: "neurology-aminoff-018", name: "عفونت‌های سیستم عصبی (مننژیت و آنسفالیت)", minutes: 150, difficulty: 3 },
      { id: "neurology-aminoff-019", name: "اختلالات حرکتی غیرارادی", minutes: 120, difficulty: 3 },
      { id: "neurology-aminoff-020", name: "اختلالات نخاعی", minutes: 120, difficulty: 3 },
    ],
  },
  {
    id: "psychiatry-dahrfar",
    name: "روانپزشکی (داهفری)",
    color: "#a855f7",
    topics: [
      { id: "psychiatry-dahrfar-001", name: "مبانی علوم رفتاری", minutes: 90, difficulty: 1 },
      { id: "psychiatry-dahrfar-002", name: "مصاحبه و ارزیابی روانپزشکی", minutes: 90, difficulty: 2 },
      { id: "psychiatry-dahrfar-003", name: "اختلالات افسردگی", minutes: 150, difficulty: 3 },
      { id: "psychiatry-dahrfar-004", name: "اختلالات دوقطبی", minutes: 150, difficulty: 3 },
      { id: "psychiatry-dahrfar-005", name: "اسکیزوفرنی و اختلالات سایکوتیک", minutes: 180, difficulty: 3 },
      { id: "psychiatry-dahrfar-006", name: "اختلالات اضطرابی", minutes: 120, difficulty: 2 },
      { id: "psychiatry-dahrfar-007", name: "اختلالات وسواسی-جبری (OCD)", minutes: 120, difficulty: 3 },
      { id: "psychiatry-dahrfar-008", name: "اختلالات تروما و استرس", minutes: 120, difficulty: 2 },
      { id: "psychiatry-dahrfar-009", name: "اختلالات جسمانی-علائم", minutes: 120, difficulty: 2 },
      { id: "psychiatry-dahrfar-010", name: "اختلالات خوردن", minutes: 120, difficulty: 2 },
      { id: "psychiatry-dahrfar-011", name: "اختلالات خواب", minutes: 90, difficulty: 2 },
      { id: "psychiatry-dahrfar-012", name: "اختلالات جنسی", minutes: 90, difficulty: 2 },
      { id: "psychiatry-dahrfar-013", name: "اختلالات شخصیت", minutes: 150, difficulty: 3 },
      { id: "psychiatry-dahrfar-014", name: "سوءمصرف مواد و اعتیاد", minutes: 120, difficulty: 3 },
      { id: "psychiatry-dahrfar-015", name: "روانپزشکی کودکی و نوجوانی", minutes: 150, difficulty: 2 },
      { id: "psychiatry-dahrfar-016", name: "روانپزشکی سالمندان", minutes: 90, difficulty: 2 },
      { id: "psychiatry-dahrfar-017", name: "روان‌درمانی و اصول درمان", minutes: 120, difficulty: 2 },
      { id: "psychiatry-dahrfar-018", name: "فارماکولوژی روانپزشکی", minutes: 150, difficulty: 3 },
      { id: "psychiatry-dahrfar-019", name: "اورژانس‌های روانپزشکی و خودکشی", minutes: 120, difficulty: 3 },
      { id: "psychiatry-dahrfar-020", name: "اخلاق در روانپزشکی", minutes: 60, difficulty: 1 },
    ],
  },
  {
    id: "dermatology-moazami",
    name: "پوست (معظمی)",
    color: "#f97316",
    topics: [
      { id: "dermatology-moazami-001", name: "آناتومی و فیزیولوژی پوست", minutes: 90, difficulty: 1 },
      { id: "dermatology-moazami-002", name: "ضایعات اولیه و ثانویه پوستی", minutes: 120, difficulty: 2 },
      { id: "dermatology-moazami-003", name: "درماتیت تماسی و آتوپیک", minutes: 120, difficulty: 2 },
      { id: "dermatology-moazami-004", name: "پسوریازیس و لیکن‌پلان", minutes: 150, difficulty: 3 },
      { id: "dermatology-moazami-005", name: "عفونت‌های باکتریال پوست", minutes: 120, difficulty: 2 },
      { id: "dermatology-moazami-006", name: "عفونت‌های قارچی پوست", minutes: 120, difficulty: 2 },
      { id: "dermatology-moazami-007", name: "عفونت‌های ویروسی پوست (زگیل، تبخال، زونا)", minutes: 150, difficulty: 2 },
      { id: "dermatology-moazami-008", name: "بیماری‌های خودایمنی پوست (پمفیگوس و پمفیگوئید)", minutes: 150, difficulty: 3 },
      { id: "dermatology-moazami-009", name: "لوپوس و درماتومیوزیت پوستی", minutes: 120, difficulty: 3 },
      { id: "dermatology-moazami-010", name: "آکنه و روزاسه", minutes: 120, difficulty: 2 },
      { id: "dermatology-moazami-011", name: "تومورهای خوش‌خیم پوست", minutes: 90, difficulty: 2 },
      { id: "dermatology-moazami-012", name: "ملانوما و کارسینوم سلول‌های پوست", minutes: 150, difficulty: 3 },
      { id: "dermatology-moazami-013", name: "بیماری‌های مو و ناخن", minutes: 120, difficulty: 2 },
      { id: "dermatology-moazami-014", name: "بیماری‌های مقاربتی پوستی", minutes: 120, difficulty: 2 },
      { id: "dermatology-moazami-015", name: "واکنش‌های دارویی پوستی", minutes: 120, difficulty: 2 },
      { id: "dermatology-moazami-016", name: "کهیر و آنژیواِدِم", minutes: 90, difficulty: 2 },
    ],
  },
  {
    id: "pathology-robbins",
    name: "پاتولوژی (رابینز)",
    color: "#dc2626",
    topics: [
      { id: "pathology-robbins-001", name: "مقدمه‌ای بر پاتولوژی و سازوکار بیماری", minutes: 120, difficulty: 1 },
      { id: "pathology-robbins-002", name: "آسیب سلولی و مرگ سلولی", minutes: 150, difficulty: 2 },
      { id: "pathology-robbins-003", name: "التهاب حاد و مزمن", minutes: 150, difficulty: 2 },
      { id: "pathology-robbins-004", name: "ترمیم و بازسازی بافتی", minutes: 120, difficulty: 2 },
      { id: "pathology-robbins-005", name: "همودینامیک و اختلالات گردش خون", minutes: 150, difficulty: 3 },
      { id: "pathology-robbins-006", name: "اختلالات ژنتیکی و بیماری‌ها", minutes: 150, difficulty: 3 },
      { id: "pathology-robbins-007", name: "اختلالات سیستم ایمنی", minutes: 150, difficulty: 3 },
      { id: "pathology-robbins-008", name: "نئوپلازی خوش‌خیم و بدخیم", minutes: 180, difficulty: 3 },
      { id: "pathology-robbins-009", name: "پاتولوژی قلبی: بیماری‌های قلب", minutes: 180, difficulty: 3 },
      { id: "pathology-robbins-010", name: "پاتولوژی قلبی: کاردیومیوپاتی و تومورها", minutes: 120, difficulty: 3 },
      { id: "pathology-robbins-011", name: "پاتولوژی سیستم عصبی مرکزی: تومورها", minutes: 150, difficulty: 3 },
      { id: "pathology-robbins-012", name: "پاتولوژی ریه", minutes: 150, difficulty: 3 },
      { id: "pathology-robbins-013", name: "پاتولوژی کلیه و سیستم جمع‌آوری", minutes: 150, difficulty: 3 },
      { id: "pathology-robbins-014", name: "پاتولوژی دستگاه گوارش و کبد", minutes: 180, difficulty: 3 },
      { id: "pathology-robbins-015", name: "پاتولوژی پانکراس و مجاری صفراوی", minutes: 120, difficulty: 3 },
      { id: "pathology-robbins-016", name: "پاتولوژی سیستم تناسلی مرد", minutes: 120, difficulty: 2 },
      { id: "pathology-robbins-017", name: "پاتولوژی سیستم تناسلی زن و پستان", minutes: 180, difficulty: 3 },
      { id: "pathology-robbins-018", name: "پاتولوژی سیستم غدد درون‌ریز", minutes: 150, difficulty: 3 },
      { id: "pathology-robbins-019", name: "پاتولوژی تومورهای استخوان و بافت نرم", minutes: 150, difficulty: 3 },
      { id: "pathology-robbins-020", name: "پاتولوژی پوست", minutes: 150, difficulty: 2 },
      { id: "pathology-robbins-021", name: "عفونت‌ها در پاتولوژی", minutes: 150, difficulty: 2 },
      { id: "pathology-robbins-022", name: "بیماری‌های محیطی و تغذیه‌ای", minutes: 120, difficulty: 2 },
    ],
  },
  {
    id: "orthopedics-alamiharandi",
    name: "ارتوپدی (اعلمی‌هرندی)",
    color: "#0d9488",
    topics: [
      { id: "orthopedics-alamiharandi-001", name: "اصول و مبانی ارتوپدی", minutes: 90, difficulty: 1 },
      { id: "orthopedics-alamiharandi-002", name: "شکستگی‌ها و اصول درمان", minutes: 150, difficulty: 2 },
      { id: "orthopedics-alamiharandi-003", name: "شکستگی اندام فوقانی", minutes: 150, difficulty: 3 },
      { id: "orthopedics-alamiharandi-004", name: "شکستگی اندام تحتانی", minutes: 150, difficulty: 3 },
      { id: "orthopedics-alamiharandi-005", name: "شکستگی لگن و حفره استابولوم", minutes: 120, difficulty: 3 },
      { id: "orthopedics-alamiharandi-006", name: "دررفتگی‌ها و آسیب لیگامان‌ها", minutes: 120, difficulty: 2 },
      { id: "orthopedics-alamiharandi-007", name: "آسیب‌های زانو (ACL و PCL)", minutes: 150, difficulty: 3 },
      { id: "orthopedics-alamiharandi-008", name: "آسیب‌های شانه و منیسک", minutes: 120, difficulty: 3 },
      { id: "orthopedics-alamiharandi-009", name: "بیماری‌های ستون فقرات", minutes: 150, difficulty: 3 },
      { id: "orthopedics-alamiharandi-010", name: "آرتریت و بیماری‌های مفصلی", minutes: 120, difficulty: 2 },
      { id: "orthopedics-alamiharandi-011", name: "تومورهای استخوان و بافت نرم", minutes: 120, difficulty: 3 },
      { id: "orthopedics-alamiharandi-012", name: "عفونت استخوان و مفصل (استئومیلیت)", minutes: 120, difficulty: 2 },
      { id: "orthopedics-alamiharandi-013", name: "بدشکلی‌های مادرزادی اندام‌ها", minutes: 120, difficulty: 2 },
      { id: "orthopedics-alamiharandi-014", name: "بیماری‌های لگن و مفصل ران", minutes: 120, difficulty: 3 },
      { id: "orthopedics-alamiharandi-015", name: "بیماری‌های پا و مچ پا", minutes: 90, difficulty: 2 },
      { id: "orthopedics-alamiharandi-016", name: "پانسمان و گچ‌گیری و کشش", minutes: 90, difficulty: 1 },
    ],
  },
  {
    id: "urology-simforoush",
    name: "اورولوژی (سیم‌فروش)",
    color: "#0284c7",
    topics: [
      { id: "urology-simforoush-001", name: "آناتومی و فیزیولوژی دستگاه ادراری", minutes: 90, difficulty: 1 },
      { id: "urology-simforoush-002", name: "بررسی بیمار اورولوژی", minutes: 90, difficulty: 2 },
      { id: "urology-simforoush-003", name: "هماتوری و بررسی توده کلیوی", minutes: 120, difficulty: 2 },
      { id: "urology-simforoush-004", name: "سنگ‌های دستگاه ادراری", minutes: 150, difficulty: 3 },
      { id: "urology-simforoush-005", name: "عفونت‌های دستگاه ادراری", minutes: 120, difficulty: 2 },
      { id: "urology-simforoush-006", name: "هیپerspلاسی خوش‌خیم پروستات (BPH)", minutes: 120, difficulty: 2 },
      { id: "urology-simforoush-007", name: "سرطان پروستات", minutes: 150, difficulty: 3 },
      { id: "urology-simforoush-008", name: "سرطان مثانه", minutes: 120, difficulty: 3 },
      { id: "urology-simforoush-009", name: "سرطان کلیه", minutes: 120, difficulty: 3 },
      { id: "urology-simforoush-010", name: "سرطان بیضه", minutes: 120, difficulty: 3 },
      { id: "urology-simforoush-011", name: "تومورهای آلت تناسلی", minutes: 90, difficulty: 2 },
      { id: "urology-simforoush-012", name: "واریکوسل و ناباروری مرد", minutes: 120, difficulty: 2 },
      { id: "urology-simforoush-013", name: "اختلالات نعوظ", minutes: 90, difficulty: 2 },
      { id: "urology-simforoush-014", name: "ترومای دستگاه ادراری", minutes: 120, difficulty: 3 },
      { id: "urology-simforoush-015", name: "انسداد مجاری ادراری", minutes: 90, difficulty: 2 },
      { id: "urology-simforoush-016", name: "بیماری‌های مادرزادی دستگاه ادراری", minutes: 120, difficulty: 2 },
      { id: "urology-simforoush-017", name: "بی‌اختیاری ادرار", minutes: 90, difficulty: 2 },
      { id: "urology-simforoush-018", name: "نارسایی مزمن کلیه در اورولوژی", minutes: 90, difficulty: 2 },
      { id: "urology-simforoush-019", name: "پیوند کلیه", minutes: 90, difficulty: 3 },
      { id: "urology-simforoush-020", name: "بیماری‌های مقعد و رکتوم در اورولوژی", minutes: 90, difficulty: 2 },
    ],
  },
  {
    id: "ophthalmology-javadi",
    name: "چشم‌پزشکی (جوادی)",
    color: "#2563eb",
    topics: [
      { id: "ophthalmology-javadi-001", name: "آناتومی و فیزیولوژی چشم", minutes: 120, difficulty: 1 },
      { id: "ophthalmology-javadi-002", name: "بررسی بیمار چشمی و معاینه", minutes: 90, difficulty: 2 },
      { id: "ophthalmology-javadi-003", name: "خطای انکساری و عیوب انکساری", minutes: 120, difficulty: 2 },
      { id: "ophthalmology-javadi-004", name: "قرنیه: بیماری‌ها و عفونت‌ها", minutes: 120, difficulty: 2 },
      { id: "ophthalmology-javadi-005", name: "صلبیه و صلبیوکرنیتیس", minutes: 90, difficulty: 2 },
      { id: "ophthalmology-javadi-006", name: "آب مروارید (کاتاراکت)", minutes: 120, difficulty: 2 },
      { id: "ophthalmology-javadi-007", name: "آب سیاه (گلوکوم)", minutes: 150, difficulty: 3 },
      { id: "ophthalmology-javadi-008", name: "شبکیه: رتینوپاتی دیابتی", minutes: 150, difficulty: 3 },
      { id: "ophthalmology-javadi-009", name: "جدایی شبکیه (رتینال دِتچمنت)", minutes: 120, difficulty: 3 },
      { id: "ophthalmology-javadi-010", name: "دژنراسیون ماکولا (AMD)", minutes: 120, difficulty: 3 },
      { id: "ophthalmology-javadi-011", name: "انسداد عروق شبکیه", minutes: 120, difficulty: 3 },
      { id: "ophthalmology-javadi-012", name: "یووئیت و التهاب داخل چشمی", minutes: 120, difficulty: 3 },
      { id: "ophthalmology-javadi-013", name: "انحراف چشم (استرابیسم)", minutes: 120, difficulty: 2 },
      { id: "ophthalmology-javadi-014", name: "بیماری‌های پلک و مجاری اشکی", minutes: 90, difficulty: 2 },
      { id: "ophthalmology-javadi-015", name: "تومورهای چشمی", minutes: 120, difficulty: 3 },
      { id: "ophthalmology-javadi-016", name: "ترومای چشم", minutes: 120, difficulty: 3 },
      { id: "ophthalmology-javadi-017", name: "اورژانس‌های چشمی", minutes: 120, difficulty: 2 },
      { id: "ophthalmology-javadi-018", name: "نوروافتالمولوژی", minutes: 120, difficulty: 3 },
      { id: "ophthalmology-javadi-019", name: "بیماری‌های چشمی کودکان", minutes: 120, difficulty: 2 },
      { id: "ophthalmology-javadi-020", name: "عوارض چشمی بیماری‌های سیستمیک", minutes: 120, difficulty: 2 },
    ],
  },
  {
    id: "ent-goldenberg",
    name: "گوش و حلق و بینی (گلدنبرگ)",
    color: "#16a34a",
    topics: [
      { id: "ent-goldenberg-001", name: "آناتومی گوش، حلق و بینی", minutes: 90, difficulty: 1 },
      { id: "ent-goldenberg-002", name: "بررسی بیمار ENT و معاینه", minutes: 90, difficulty: 1 },
      { id: "ent-goldenberg-003", name: "عفونت‌های گوش خارجی", minutes: 90, difficulty: 2 },
      { id: "ent-goldenberg-004", name: "اتیت میانی حاد و مزمن", minutes: 150, difficulty: 3 },
      { id: "ent-goldenberg-005", name: "کلستاتوم و عوارض آن", minutes: 120, difficulty: 3 },
      { id: "ent-goldenberg-006", name: "کم‌شنوایی و وزوز گوش", minutes: 120, difficulty: 2 },
      { id: "ent-goldenberg-007", name: "بیماری منیر و سرگیجه", minutes: 150, difficulty: 3 },
      { id: "ent-goldenberg-008", name: "سینوزیت حاد و مزمن", minutes: 120, difficulty: 2 },
      { id: "ent-goldenberg-009", name: "رینیت آلرژیک و پولیپ بینی", minutes: 120, difficulty: 2 },
      { id: "ent-goldenberg-010", name: "خونریزی بینی (اپیستاکسی)", minutes: 90, difficulty: 2 },
      { id: "ent-goldenberg-011", name: "انحراف تیغه بینی و مشکلات تنفسی", minutes: 90, difficulty: 2 },
      { id: "ent-goldenberg-012", name: "فارنژیت و تonsillitis", minutes: 90, difficulty: 2 },
      { id: "ent-goldenberg-013", name: "آپنه خواب و اختلالات خواب", minutes: 120, difficulty: 3 },
      { id: "ent-goldenberg-014", name: "تومورهای سر و گردن", minutes: 150, difficulty: 3 },
      { id: "ent-goldenberg-015", name: "سرطان حنجره", minutes: 120, difficulty: 3 },
      { id: "ent-goldenberg-016", name: "تومورهای غدد بزاقی", minutes: 120, difficulty: 3 },
      { id: "ent-goldenberg-017", name: "اختلالات صوت و حنجره", minutes: 90, difficulty: 2 },
      { id: "ent-goldenberg-018", name: "ترومای صورت و شکستگی‌ها", minutes: 150, difficulty: 3 },
      { id: "ent-goldenberg-019", name: "عفونت‌های عمقی گردن", minutes: 120, difficulty: 3 },
      { id: "ent-goldenberg-020", name: "جسم خارجی در گوش، بینی و حلق", minutes: 60, difficulty: 1 },
    ],
  },
  {
    id: "medical-ethics-reaghib",
    name: "اخلاق پزشکی",
    color: "#64748b",
    topics: [
      { id: "medical-ethics-001", name: "اصول اخلاق پزشکی: خودمختاری، عدالت، سودرسانی", minutes: 90, difficulty: 1 },
      { id: "medical-ethics-002", name: "رضایت آگاهانه بیمار", minutes: 90, difficulty: 2 },
      { id: "medical-ethics-003", name: "رازداری پزشکی", minutes: 90, difficulty: 2 },
      { id: "medical-ethics-004", name: "حق بیمار و حقوق شهروندی", minutes: 90, difficulty: 1 },
      { id: "medical-ethics-005", name: "مسئولیت حرفه‌ای و قصور پزشکی", minutes: 120, difficulty: 2 },
      { id: "medical-ethics-006", name: "اتیکت پزشکی و ارتباط با بیمار", minutes: 90, difficulty: 1 },
      { id: "medical-ethics-007", name: "اتانازی و مسائل پایان زندگی", minutes: 90, difficulty: 2 },
      { id: "medical-ethics-008", name: "سقط درمانی و اخلاق باروری", minutes: 90, difficulty: 2 },
      { id: "medical-ethics-009", name: "اخلاق در تحقیقات پزشکی", minutes: 90, difficulty: 2 },
      { id: "medical-ethics-010", name: "تخصیص منابع و عدالت در سلامت", minutes: 90, difficulty: 2 },
    ],
  },
  {
    id: "statistics-epidemiology",
    name: "آمار و اپیدمیولوژی",
    color: "#ca8a04",
    topics: [
      // آمار پزشکی (Medical Statistics at a Glance)
      { id: "stats-001", name: "مقدمه‌ای بر آمار: انواع داده و متغیرها", minutes: 90, difficulty: 1 },
      { id: "stats-002", name: "توزیع نرمال و شاخص‌های مرکزی", minutes: 120, difficulty: 2 },
      { id: "stats-003", name: "شاخص‌های پراکندگی", minutes: 90, difficulty: 2 },
      { id: "stats-004", name: "آزمون t و مقایسه میانگین‌ها", minutes: 120, difficulty: 3 },
      { id: "stats-005", name: "آزمون کای مربع و نسبت‌ها", minutes: 120, difficulty: 3 },
      { id: "stats-006", name: "همبستگی و رگرسیون", minutes: 120, difficulty: 3 },
      { id: "stats-007", name: "نمونه‌گیری و تخمین", minutes: 90, difficulty: 2 },
      { id: "stats-008", name: "آزمون فرض (Hypothesis Testing)", minutes: 120, difficulty: 3 },
      { id: "stats-009", name: "ANOVA و مقایسه چند گروهی", minutes: 90, difficulty: 3 },
      { id: "stats-010", name: "آزمون‌های ناپارامتریک", minutes: 90, difficulty: 2 },
      { id: "stats-011", name: "تحلیل بقا و منحنی کاپلان-مایر", minutes: 90, difficulty: 3 },
      { id: "stats-012", name: "مطالعات تشخیصی (حساسیت و ویژگی)", minutes: 120, difficulty: 3 },
      // اپیدمیولوژی (اپیدمیولوژی بیماری‌های شایع ایران)
      { id: "epi-001", name: "مقدمه‌ای بر اپیدمیولوژی", minutes: 90, difficulty: 1 },
      { id: "epi-002", name: "فشارخون و بیماری‌های قلبی-عروقی", minutes: 120, difficulty: 2 },
      { id: "epi-003", name: "دیابت ملیتوس", minutes: 120, difficulty: 2 },
      { id: "epi-004", name: "چاقی و اضافه وزن", minutes: 90, difficulty: 2 },
      { id: "epi-005", name: "پوکی استخوان", minutes: 90, difficulty: 2 },
      { id: "epi-006", name: "کم‌کاری تیروئید نوزادان", minutes: 60, difficulty: 1 },
      { id: "epi-007", name: "سوءتغذیه پروتئین-انرژی کودکان", minutes: 90, difficulty: 2 },
      { id: "epi-008", name: "کم‌خونی فقر آهن", minutes: 90, difficulty: 2 },
      { id: "epi-009", name: "بیماری‌های عفونی واگیر (سل، مالاریا، هاری و...)", minutes: 150, difficulty: 2 },
      { id: "epi-010", name: "بیماری‌های غیرواگیر (قلبی، سرطان و...)", minutes: 150, difficulty: 2 },
      { id: "epi-011", name: "سرطان‌های شایع (پستان، معده، روده و...)", minutes: 150, difficulty: 3 },
      { id: "epi-012", name: "سلامت روان و افسردگی در ایران", minutes: 90, difficulty: 2 },
      { id: "epi-013", name: "حوادث جاده‌ای و آسیب‌ها", minutes: 90, difficulty: 2 },
      { id: "epi-014", name: "دخانیات و اعتیاد", minutes: 90, difficulty: 2 },
      { id: "epi-015", name: "مقدمه‌ای بر روش‌های تحقیق اپیدمیولوژیک", minutes: 120, difficulty: 2 },
      { id: "epi-016", name: "مقابله با مقاومت میکروبی و آنتی‌بیوتیک‌ها", minutes: 90, difficulty: 2 },
    ],
  },
  {
    id: "immunology-helbert",
    name: "ایمونولوژی (هِلبرت)",
    color: "#e11d48",
    topics: [
      { id: "immunology-helbert-001", name: "مفاهیم پایه سیستم ایمنی", minutes: 120, difficulty: 1 },
      { id: "immunology-helbert-002", name: "اندام‌ها و بافت‌های لنفاوی", minutes: 120, difficulty: 2 },
      { id: "immunology-helbert-003", name: "ایمنی ذاتی و اکتسابی", minutes: 150, difficulty: 2 },
      { id: "immunology-helbert-004", name: "آنتی‌بادی‌ها و سیستم کمپلمان", minutes: 150, difficulty: 3 },
      { id: "immunology-helbert-005", name: "لنفوسیت‌های T و B", minutes: 150, difficulty: 3 },
      { id: "immunology-helbert-006", name: "پردازش و ارائه آنتی‌ژن (MHC)", minutes: 120, difficulty: 3 },
      { id: "immunology-helbert-007", name: "سایتوکاین‌ها و کموکاین‌ها", minutes: 120, difficulty: 2 },
      { id: "immunology-helbert-008", name: "ایمنی در برابر عفونت‌ها و واکسن‌ها", minutes: 150, difficulty: 2 },
      { id: "immunology-helbert-009", name: "واکنش افزایش حساسیت فوری (نوع ۱): آلرژی", minutes: 120, difficulty: 3 },
      { id: "immunology-helbert-010", name: "واکنش افزایش حساسیت نوع ۲", minutes: 90, difficulty: 3 },
      { id: "immunology-helbert-011", name: "بیماری کمپلکس ایمنی (نوع ۳)", minutes: 90, difficulty: 3 },
      { id: "immunology-helbert-012", name: "واکنش افزایش حساسیت تاخیری (نوع ۴)", minutes: 120, difficulty: 3 },
      { id: "immunology-helbert-013", name: "نحوه ایجاد بیماری خودایمنی", minutes: 120, difficulty: 3 },
      { id: "immunology-helbert-014", name: "نقص ایمنی اولیه", minutes: 120, difficulty: 3 },
      { id: "immunology-helbert-015", name: "نقص ایمنی ثانویه", minutes: 90, difficulty: 2 },
      { id: "immunology-helbert-016", name: "پیوند و رد پیوند", minutes: 120, difficulty: 3 },
      { id: "immunology-helbert-017", name: "ایمونولوژی تومور", minutes: 120, difficulty: 3 },
    ],
  },
  {
    id: "genetics-emery",
    name: "ژنتیک پزشکی (امری)",
    color: "#be185d",
    topics: [
      { id: "genetics-emery-001", name: "مبانی ژنتیک مولکولی", minutes: 120, difficulty: 2 },
      { id: "genetics-emery-002", name: "ساختار DNA و بیان ژن", minutes: 120, difficulty: 2 },
      { id: "genetics-emery-003", name: "الگوی وراثت مندلی", minutes: 120, difficulty: 2 },
      { id: "genetics-emery-004", name: "وراثت اتوزومال غالب و مغلوب", minutes: 150, difficulty: 3 },
      { id: "genetics-emery-005", name: "وراثت وابسته به X", minutes: 120, difficulty: 3 },
      { id: "genetics-emery-006", name: "اختلالات کروموزومی (آنوپلوئیدی و...)", minutes: 150, difficulty: 3 },
      { id: "genetics-emery-007", name: "سندرم داون و سایر تروزومی‌ها", minutes: 120, difficulty: 2 },
      { id: "genetics-emery-008", name: "جهش‌های ژنی و بیماری‌های تک‌ژنی", minutes: 150, difficulty: 3 },
      { id: "genetics-emery-009", name: "ژنتیک سرطان", minutes: 120, difficulty: 3 },
      { id: "genetics-emery-010", name: "مشاوره ژنتیک و تشخیص قبل از تولد", minutes: 120, difficulty: 2 },
      { id: "genetics-emery-011", name: "اپی‌ژنتیک و ایمپرینتینگ", minutes: 120, difficulty: 3 },
      { id: "genetics-emery-012", name: "بیماری‌های میتوکندریایی", minutes: 90, difficulty: 3 },
      { id: "genetics-emery-013", name: "ژنتیک جمعیت و غربالگری", minutes: 90, difficulty: 2 },
      { id: "genetics-emery-014", name: "درمان ژنی و فناوری‌های نوین", minutes: 90, difficulty: 2 },
    ],
  },
  {
    id: "medical-physics",
    name: "فیزیک پزشکی",
    color: "#475569",
    topics: [
      { id: "med-physics-001", name: "مبانی فیزیک پرتوشناسی", minutes: 90, difficulty: 1 },
      { id: "med-physics-002", name: "انواع پرتوهای یونیزان و غیریونیزان", minutes: 90, difficulty: 2 },
      { id: "med-physics-003", name: "اصول تصویربرداری اشعه ایکس", minutes: 120, difficulty: 2 },
      { id: "med-physics-004", name: "اصول CT Scan و فیزیک آن", minutes: 120, difficulty: 3 },
      { id: "med-physics-005", name: "اصول MRI و فیزیک آن", minutes: 120, difficulty: 3 },
      { id: "med-physics-006", name: "اصول سونوگرافی و فیزیک امواج صوتی", minutes: 120, difficulty: 2 },
      { id: "med-physics-007", name: "پزشکی هسته‌ای و رادیوایزوتوپ‌ها", minutes: 120, difficulty: 3 },
      { id: "med-physics-008", name: "ایمنی پرتو و حفاظت اشعه", minutes: 90, difficulty: 2 },
      { id: "med-physics-009", name: "فیزیک رادیوتراپی", minutes: 120, difficulty: 3 },
      { id: "med-physics-010", name: "لیزر در پزشکی", minutes: 90, difficulty: 2 },
      { id: "med-physics-011", name: "بیوالکتریک و سیگنال‌های فیزیولوژیک", minutes: 90, difficulty: 2 },
      { id: "med-physics-012", name: "بیومکانیک و فیزیک عضلات", minutes: 90, difficulty: 2 },
    ],
  },
  {
    id: "nutrition",
    name: "تغذیه (کلی و رژیم‌درمانی)",
    color: "#ea580c",
    topics: [
      { id: "nutrition-001", name: "مروری بر تغذیه و سلامت", minutes: 90, difficulty: 1 },
      { id: "nutrition-002", name: "کربوهیدرات‌ها: مونوساکاریدها و دی‌ساکاریدها", minutes: 120, difficulty: 2 },
      { id: "nutrition-003", name: "پلی‌ساکاریدها و فیبر", minutes: 90, difficulty: 2 },
      { id: "nutrition-004", name: "لیپیدها: تری‌گلیسیریدها و اسیدهای چرب", minutes: 120, difficulty: 2 },
      { id: "nutrition-005", name: "پروتئین و سلامت", minutes: 120, difficulty: 2 },
      { id: "nutrition-006", name: "کمبود پروتئین و سوءتغذیه", minutes: 120, difficulty: 2 },
      { id: "nutrition-007", name: "تنظیم قند خون", minutes: 90, difficulty: 2 },
      { id: "nutrition-008", name: "مدیریت وزن: انرژی ورودی و خروجی", minutes: 120, difficulty: 2 },
      { id: "nutrition-009", name: "ویتامین‌های محلول در چربی (A, D, E, K)", minutes: 150, difficulty: 2 },
      { id: "nutrition-010", name: "ویتامین‌های محلول در آب (B, C)", minutes: 150, difficulty: 2 },
      { id: "nutrition-011", name: "مواد معدنی: کلسیم، منیزیم، آهن", minutes: 120, difficulty: 2 },
      { id: "nutrition-012", name: "مواد معدنی: روی، سلنیوم، ید، مس", minutes: 120, difficulty: 2 },
      { id: "nutrition-013", name: "تغذیه قبل و حین بارداری", minutes: 120, difficulty: 2 },
      { id: "nutrition-014", name: "تغذیه شیرخوار و کودکان", minutes: 120, difficulty: 2 },
      { id: "nutrition-015", name: "تغذیه والدینی (پارنترال)", minutes: 90, difficulty: 3 },
    ],
  },
  {
    id: "cardiology-nematpour",
    name: "قلب و عروق (نعمتی‌پور)",
    color: "#dc2626",
    topics: [
      { id: "cardiology-nematpour-001", name: "آناتومی و فیزیولوژی قلب", minutes: 120, difficulty: 2 },
      { id: "cardiology-nematpour-002", name: "بررسی بیمار قلبی و اکوکاردیوگرافی", minutes: 120, difficulty: 2 },
      { id: "cardiology-nematpour-003", name: "الکتروفیزیولوژی قلب", minutes: 120, difficulty: 3 },
      { id: "cardiology-nematpour-004", name: "آریتمی‌های فوق بطنی", minutes: 150, difficulty: 3 },
      { id: "cardiology-nematpour-005", name: "آریتمی‌های بطنی", minutes: 150, difficulty: 3 },
      { id: "cardiology-nematpour-006", name: "بلوک‌های دهلیزی-بطنی", minutes: 120, difficulty: 3 },
      { id: "cardiology-nematpour-007", name: "سندرم‌های پیش‌انگیزانه (WPW)", minutes: 90, difficulty: 3 },
      { id: "cardiology-nematpour-008", name: "ایسکمی قلبی: آنژین پایدار", minutes: 150, difficulty: 3 },
      { id: "cardiology-nematpour-009", name: "سندرم حاد کرونری (STEMI و NSTEMI)", minutes: 180, difficulty: 3 },
      { id: "cardiology-nematpour-010", name: "نارسایی قلبی حاد و مزمن", minutes: 180, difficulty: 3 },
      { id: "cardiology-nematpour-011", name: "شوک قلبی‌ریوی (کاردیوژنیک)", minutes: 120, difficulty: 3 },
      { id: "cardiology-nematpour-012", name: "بیماری‌های دریچه‌ای: میترال", minutes: 150, difficulty: 3 },
      { id: "cardiology-nematpour-013", name: "بیماری‌های دریچه‌ای: آئورت", minutes: 150, difficulty: 3 },
      { id: "cardiology-nematpour-014", name: "اندوکاردیت", minutes: 120, difficulty: 3 },
      { id: "cardiology-nematpour-015", name: "پریکاردیت و افیوژن پریکارد", minutes: 120, difficulty: 2 },
      { id: "cardiology-nematpour-016", name: "کاردیومیوپاتی‌ها", minutes: 150, difficulty: 3 },
      { id: "cardiology-nematpour-017", name: "بیماری‌های آئورت (دایسکشن)", minutes: 120, difficulty: 3 },
      { id: "cardiology-nematpour-018", name: "بیماری‌های مادرزادی قلب", minutes: 150, difficulty: 3 },
      { id: "cardiology-nematpour-019", name: "تومورهای قلبی", minutes: 90, difficulty: 2 },
      { id: "cardiology-nematpour-020", name: "اصول RCP و احیای قلبی", minutes: 120, difficulty: 2 },
    ],
  },
];
