import type { Difficulty } from "../types";

export interface SampleTopic {
  /** Permanent key: never derive this from the title or the current array position. */
  id: string;
  aliases?: string[];
  name: string;
  minutes: number;
  difficulty: Difficulty;
}

export interface SampleSubject {
  id: string;
  aliases?: string[];
  name: string;
  color: string;
  topics: SampleTopic[];
}

/**
 * سرفصل‌های پیشنهادی برای برنامه‌ریزی مطالعه؛ نه فهرست دقیق یک ویرایش خاص.
 * زمان و حجم‌ها تخمینی‌اند و کاربر می‌تواند همه‌ی آن‌ها را ویرایش کند.
 * شناسه‌ها دائمی‌اند؛ برای موضوع تازه کلید جدید بسازید، کلید قدیمی را تغییر ندهید.
 */
export const SAMPLE_SUBJECTS: SampleSubject[] = [
  {
    id: "surgery-lawrence",
    name: "جراحی (لارنس)",
    color: "#8b5cf6",
    topics: [
      { id: "surgery-lawrence-001", name: "ارزیابی قبل از عمل و مراقبت از بیمار جراحی", minutes: 120, difficulty: 2 },
      { id: "surgery-lawrence-002", name: "مایعات، الکترولیت‌ها و تعادل اسید و باز", minutes: 150, difficulty: 3 },
      { id: "surgery-lawrence-003", name: "تغذیه‌ی جراحی", minutes: 90, difficulty: 2 },
      { id: "surgery-lawrence-004", name: "خونریزی جراحی و اختلالات انعقادی", minutes: 120, difficulty: 3 },
      { id: "surgery-lawrence-005", name: "شوک", minutes: 120, difficulty: 3 },
      { id: "surgery-lawrence-006", name: "مراقبت‌های ویژه‌ی جراحی", minutes: 120, difficulty: 3 },
      { id: "surgery-lawrence-007", name: "زخم و ترمیم زخم", minutes: 90, difficulty: 2 },
      { id: "surgery-lawrence-008", name: "عفونت‌های جراحی", minutes: 120, difficulty: 2 },
      { id: "surgery-lawrence-009", name: "تروما", minutes: 180, difficulty: 3 },
      { id: "surgery-lawrence-010", name: "سوختگی", minutes: 120, difficulty: 2 },
      { id: "surgery-lawrence-011", name: "دیواره‌ی شکم و فتق", minutes: 120, difficulty: 2 },
      { id: "surgery-lawrence-012", name: "مری", minutes: 120, difficulty: 3 },
      { id: "surgery-lawrence-013", name: "معده و دوازدهه", minutes: 150, difficulty: 3 },
      { id: "surgery-lawrence-014", name: "روده‌ی باریک و آپاندیس", minutes: 150, difficulty: 2 },
      { id: "surgery-lawrence-015", name: "کولون، رکتوم و مقعد", minutes: 150, difficulty: 3 },
      { id: "surgery-lawrence-016", name: "مجاری صفراوی", minutes: 150, difficulty: 3 },
      { id: "surgery-lawrence-017", name: "پانکراس", minutes: 120, difficulty: 3 },
      { id: "surgery-lawrence-018", name: "کبد", minutes: 120, difficulty: 3 },
      { id: "surgery-lawrence-019", name: "پستان", minutes: 120, difficulty: 2 },
      { id: "surgery-lawrence-020", name: "جراحی غدد درون‌ریز", minutes: 120, difficulty: 3 },
      { id: "surgery-lawrence-021", name: "طحال و غدد لنفاوی", minutes: 90, difficulty: 2 },
      { id: "surgery-lawrence-022", name: "بیماری‌های عروقی", minutes: 150, difficulty: 3 },
      { id: "surgery-lawrence-023", name: "پیوند اعضا", minutes: 90, difficulty: 2 },
      { id: "surgery-lawrence-024", name: "انکولوژی جراحی", minutes: 120, difficulty: 2 },
      { id: "surgery-lawrence-025", name: "تکنیک‌ها و مهارت‌های جراحی", minutes: 90, difficulty: 2 },
    ],
  },
  {
    id: "gynecology-beckmann",
    name: "زنان (بکمن)",
    color: "#ec4899",
    topics: [
      { id: "gynecology-beckmann-001", name: "معاینه‌ی سلامت زنان و مدیریت مراقبت", minutes: 90, difficulty: 2 },
      { id: "gynecology-beckmann-002", name: "نقش متخصص زنان در غربالگری و مراقبت پیشگیرانه", minutes: 90, difficulty: 1 },
      { id: "gynecology-beckmann-003", name: "اخلاق، مسئولیت و ایمنی بیمار در زنان", minutes: 60, difficulty: 1 },
      { id: "gynecology-beckmann-004", name: "جنین‌شناسی و آناتومی", minutes: 120, difficulty: 2 },
      { id: "gynecology-beckmann-005", name: "فیزیولوژی مادر و جنین", minutes: 120, difficulty: 2 },
      { id: "gynecology-beckmann-006", name: "مراقبت قبل از بارداری", minutes: 120, difficulty: 2 },
      { id: "gynecology-beckmann-007", name: "ژنتیک و اختلالات ژنتیکی در زنان", minutes: 120, difficulty: 3 },
      { id: "gynecology-beckmann-008", name: "مراقبت حین زایمان", minutes: 150, difficulty: 2 },
      { id: "gynecology-beckmann-009", name: "زایمان غیرطبیعی و پایش جنین", minutes: 150, difficulty: 3 },
      { id: "gynecology-beckmann-010", name: "مراقبت فوری نوزاد", minutes: 90, difficulty: 2 },
      { id: "gynecology-beckmann-011", name: "مراقبت پس از زایمان", minutes: 90, difficulty: 1 },
      { id: "gynecology-beckmann-012", name: "خونریزی پس از زایمان", minutes: 120, difficulty: 3 },
      { id: "gynecology-beckmann-013", name: "حاملگی چندقلویی", minutes: 90, difficulty: 2 },
      { id: "gynecology-beckmann-014", name: "اختلالات رشد جنین (محدودیت رشد و ماکروزومی)", minutes: 120, difficulty: 3 },
      { id: "gynecology-beckmann-015", name: "زایمان زودرس", minutes: 120, difficulty: 3 },
      { id: "gynecology-beckmann-016", name: "خونریزی سه‌ماهه‌ی سوم", minutes: 120, difficulty: 3 },
      { id: "gynecology-beckmann-017", name: "پارگی زودرس پرده‌ها", minutes: 90, difficulty: 2 },
      { id: "gynecology-beckmann-018", name: "بارداری پس از موعد", minutes: 60, difficulty: 1 },
      { id: "gynecology-beckmann-019", name: "حاملگی نابجا و سقط", minutes: 120, difficulty: 3 },
      { id: "gynecology-beckmann-020", name: "اختلالات غدد درون‌ریز در بارداری", minutes: 120, difficulty: 3 },
      { id: "gynecology-beckmann-021", name: "عوارض گوارشی، کلیوی و جراحی در بارداری", minutes: 120, difficulty: 2 },
      { id: "gynecology-beckmann-022", name: "اختلالات قلبی‌عروقی و تنفسی در بارداری", minutes: 120, difficulty: 3 },
      { id: "gynecology-beckmann-023", name: "عوارض خونی و ایمونولوژیک در بارداری", minutes: 120, difficulty: 3 },
      { id: "gynecology-beckmann-024", name: "بیماری‌های عفونی در بارداری", minutes: 120, difficulty: 2 },
      { id: "gynecology-beckmann-025", name: "اختلالات عصبی و روانپزشکی در بارداری", minutes: 90, difficulty: 2 },
      { id: "gynecology-beckmann-026", name: "پیشگیری از بارداری", minutes: 120, difficulty: 2 },
      { id: "gynecology-beckmann-027", name: "عقیم‌سازی", minutes: 60, difficulty: 1 },
      { id: "gynecology-beckmann-028", name: "ولوواژینیت", minutes: 90, difficulty: 2 },
      { id: "gynecology-beckmann-029", name: "عفونت‌های منتقله‌ی جنسی", minutes: 120, difficulty: 2 },
      { id: "gynecology-beckmann-030", name: "افتادگی لگن، بی‌اختیاری ادرار و عفونت ادراری", minutes: 120, difficulty: 2 },
      { id: "gynecology-beckmann-031", name: "اندومتریوز", minutes: 90, difficulty: 2 },
      { id: "gynecology-beckmann-032", name: "دیسمنوره و درد مزمن لگن", minutes: 90, difficulty: 2 },
      { id: "gynecology-beckmann-033", name: "اختلالات پستان", minutes: 120, difficulty: 2 },
      { id: "gynecology-beckmann-034", name: "پروسیجرهای زنان", minutes: 90, difficulty: 1 },
      { id: "gynecology-beckmann-035", name: "جنسیت انسانی", minutes: 60, difficulty: 1 },
      { id: "gynecology-beckmann-036", name: "تجاوز جنسی و خشونت خانگی", minutes: 60, difficulty: 1 },
      { id: "gynecology-beckmann-037", name: "سیکل‌های تولیدمثل", minutes: 90, difficulty: 2 },
      { id: "gynecology-beckmann-038", name: "بلوغ", minutes: 90, difficulty: 2 },
      { id: "gynecology-beckmann-039", name: "آمنوره و خونریزی غیرطبیعی رحم", minutes: 150, difficulty: 3 },
      { id: "gynecology-beckmann-040", name: "هیرسوتیسم و ویریلیزاسیون", minutes: 90, difficulty: 2 },
      { id: "gynecology-beckmann-041", name: "یائسگی", minutes: 90, difficulty: 2 },
      { id: "gynecology-beckmann-042", name: "ناباروری", minutes: 150, difficulty: 3 },
      { id: "gynecology-beckmann-043", name: "سندرم پیش از قاعدگی و اختلال دیسفوریک", minutes: 60, difficulty: 1 },
      { id: "gynecology-beckmann-044", name: "زیست‌شناسی سلولی و اصول درمان سرطان", minutes: 90, difficulty: 2 },
      { id: "gynecology-beckmann-045", name: "نئوپلازی تروفوبلاستیک حاملگی", minutes: 90, difficulty: 3 },
      { id: "gynecology-beckmann-046", name: "بیماری و نئوپلازی ولو و واژن", minutes: 90, difficulty: 2 },
      { id: "gynecology-beckmann-047", name: "نئوپلازی و کارسینوم سرویکس", minutes: 120, difficulty: 3 },
      { id: "gynecology-beckmann-048", name: "لیومیوم و نئوپلازی رحم", minutes: 90, difficulty: 2 },
      { id: "gynecology-beckmann-049", name: "سرطان جسم رحم", minutes: 90, difficulty: 3 },
      { id: "gynecology-beckmann-050", name: "بیماری‌های تخمدان و آدنکس", minutes: 120, difficulty: 3 },
    ],
  },
  {
    id: "pediatrics-nelson",
    name: "اطفال (نلسون)",
    color: "#f59e0b",
    topics: [
      { id: "pediatrics-nelson-001", name: "کلیات طب اطفال", minutes: 60, difficulty: 1 },
      { id: "pediatrics-nelson-002", name: "رشد، تکامل و رفتار", minutes: 150, difficulty: 2 },
      { id: "pediatrics-nelson-003", name: "اختلالات رفتاری و روانپزشکی", minutes: 120, difficulty: 2 },
      { id: "pediatrics-nelson-004", name: "اختلالات یادگیری و تکامل", minutes: 90, difficulty: 2 },
      { id: "pediatrics-nelson-005", name: "تغذیه", minutes: 120, difficulty: 2 },
      { id: "pediatrics-nelson-006", name: "اختلالات مایعات و الکترولیت‌ها", minutes: 150, difficulty: 3 },
      { id: "pediatrics-nelson-007", name: "اورژانس، مراقبت ویژه و بیهوشی", minutes: 150, difficulty: 3 },
      { id: "pediatrics-nelson-008", name: "ژنتیک انسانی", minutes: 90, difficulty: 2 },
      { id: "pediatrics-nelson-009", name: "اختلالات متابولیک", minutes: 120, difficulty: 3 },
      { id: "pediatrics-nelson-010", name: "جنین و نوزاد", minutes: 180, difficulty: 3 },
      { id: "pediatrics-nelson-011", name: "طب نوجوانان", minutes: 90, difficulty: 2 },
      { id: "pediatrics-nelson-012", name: "ایمونولوژی", minutes: 90, difficulty: 2 },
      { id: "pediatrics-nelson-013", name: "اختلالات آلرژیک", minutes: 90, difficulty: 2 },
      { id: "pediatrics-nelson-014", name: "بیماری‌های روماتیسمی کودکان", minutes: 120, difficulty: 3 },
      { id: "pediatrics-nelson-015", name: "بیماری‌های عفونی", minutes: 180, difficulty: 3 },
      { id: "pediatrics-nelson-016", name: "دستگاه گوارش", minutes: 150, difficulty: 2 },
      { id: "pediatrics-nelson-017", name: "دستگاه تنفس", minutes: 150, difficulty: 2 },
      { id: "pediatrics-nelson-018", name: "دستگاه قلب و عروق", minutes: 150, difficulty: 3 },
      { id: "pediatrics-nelson-019", name: "بیماری‌های خون", minutes: 120, difficulty: 2 },
      { id: "pediatrics-nelson-020", name: "سرطان و تومورهای خوش‌خیم", minutes: 120, difficulty: 3 },
      { id: "pediatrics-nelson-021", name: "نفرولوژی", minutes: 120, difficulty: 3 },
      { id: "pediatrics-nelson-022", name: "اختلالات اورولوژی در شیرخواران و کودکان", minutes: 90, difficulty: 2 },
      { id: "pediatrics-nelson-023", name: "مشکلات زنان در دوران کودکی", minutes: 60, difficulty: 1 },
      { id: "pediatrics-nelson-024", name: "دستگاه غدد درون‌ریز", minutes: 120, difficulty: 2 },
      { id: "pediatrics-nelson-025", name: "دستگاه عصبی", minutes: 150, difficulty: 3 },
      { id: "pediatrics-nelson-026", name: "اختلالات عصبی‌عضلانی", minutes: 90, difficulty: 2 },
      { id: "pediatrics-nelson-027", name: "اختلالات چشم", minutes: 60, difficulty: 1 },
      { id: "pediatrics-nelson-028", name: "گوش", minutes: 60, difficulty: 1 },
      { id: "pediatrics-nelson-029", name: "پوست", minutes: 120, difficulty: 2 },
      { id: "pediatrics-nelson-030", name: "اختلالات استخوان و مفاصل", minutes: 90, difficulty: 2 },
      { id: "pediatrics-nelson-031", name: "طب توانبخشی", minutes: 60, difficulty: 1 },
      { id: "pediatrics-nelson-032", name: "سلامت محیطی", minutes: 60, difficulty: 1 },
      { id: "pediatrics-nelson-033", name: "طب آزمایشگاهی", minutes: 60, difficulty: 1 },
    ],
  },
  {
    id: "infectious-harrison",
    name: "عفونی",
    color: "#ef4444",
    topics: [
      { id: "infectious-harrison-001", name: "تب و هیپرترمی", minutes: 60, difficulty: 1 },
      { id: "infectious-harrison-002", name: "تب و راش", minutes: 90, difficulty: 2 },
      { id: "infectious-harrison-003", name: "تب با منشأ نامعلوم", minutes: 120, difficulty: 3 },
      { id: "infectious-harrison-004", name: "رویکرد به بیمار عفونی بدحال", minutes: 90, difficulty: 2 },
      { id: "infectious-harrison-005", name: "بیماری‌های اسهالی حاد عفونی و مسمومیت غذایی", minutes: 120, difficulty: 2 },
      { id: "infectious-harrison-006", name: "عفونت‌های منتقله‌ی جنسی", minutes: 120, difficulty: 2 },
      { id: "infectious-harrison-007", name: "عفونت‌های پوست، عضلات و بافت نرم", minutes: 90, difficulty: 2 },
      { id: "infectious-harrison-008", name: "استئومیلیت", minutes: 90, difficulty: 2 },
      { id: "infectious-harrison-009", name: "کلستریدیوم دیفیسیل", minutes: 60, difficulty: 2 },
      { id: "infectious-harrison-010", name: "عفونت‌های استافیلوکوکی", minutes: 90, difficulty: 2 },
      { id: "infectious-harrison-011", name: "عفونت‌های استرپتوکوکی و پنوموکوکی", minutes: 120, difficulty: 2 },
      { id: "infectious-harrison-012", name: "دیفتری", minutes: 60, difficulty: 1 },
      { id: "infectious-harrison-013", name: "بوتولیسم", minutes: 60, difficulty: 2 },
      { id: "infectious-harrison-014", name: "کزاز", minutes: 60, difficulty: 1 },
      { id: "infectious-harrison-015", name: "سالمونلوز", minutes: 90, difficulty: 2 },
      { id: "infectious-harrison-016", name: "شیگلوز", minutes: 90, difficulty: 2 },
      { id: "infectious-harrison-017", name: "وبا و سایر ویبریوها", minutes: 60, difficulty: 2 },
      { id: "infectious-harrison-018", name: "بروسلوز", minutes: 90, difficulty: 2 },
      { id: "infectious-harrison-019", name: "تب تیفوئید", minutes: 90, difficulty: 2 },
      { id: "infectious-harrison-020", name: "لپتوسپیروز", minutes: 60, difficulty: 2 },
      { id: "infectious-harrison-021", name: "تب راجعه", minutes: 60, difficulty: 1 },
      { id: "infectious-harrison-022", name: "بورلیوز لایم", minutes: 60, difficulty: 2 },
      { id: "infectious-harrison-023", name: "عفونت‌های حاد سیستم عصبی (مننژیت، آنسفالیت، آبسه مغزی)", minutes: 150, difficulty: 3 },
      { id: "infectious-harrison-024", name: "عفونت‌های ادراری", minutes: 90, difficulty: 2 },
      { id: "infectious-harrison-025", name: "اندوکاردیت عفونی", minutes: 150, difficulty: 3 },
      { id: "infectious-harrison-026", name: "پنومونی", minutes: 150, difficulty: 3 },
      { id: "infectious-harrison-027", name: "سل", minutes: 150, difficulty: 3 },
      { id: "infectious-harrison-028", name: "سپسیس شدید و شوک سپتیک", minutes: 120, difficulty: 3 },
      { id: "infectious-harrison-029", name: "آنتی‌بیوتیک‌ها", minutes: 120, difficulty: 2 },
      { id: "infectious-harrison-030", name: "عفونت‌های بیمارستانی", minutes: 90, difficulty: 2 },
      { id: "infectious-harrison-031", name: "مونونوکلئوز عفونی", minutes: 60, difficulty: 1 },
      { id: "infectious-harrison-032", name: "آنفلوانزا", minutes: 90, difficulty: 2 },
      { id: "infectious-harrison-033", name: "سرخجه", minutes: 60, difficulty: 1 },
      { id: "infectious-harrison-034", name: "سرخک", minutes: 60, difficulty: 1 },
      { id: "infectious-harrison-035", name: "عفونت‌های واریسلا زوستر", minutes: 90, difficulty: 2 },
      { id: "infectious-harrison-036", name: "هاری", minutes: 60, difficulty: 1 },
      { id: "infectious-harrison-037", name: "اوریون", minutes: 60, difficulty: 1 },
      { id: "infectious-harrison-038", name: "HIV و ایدز", minutes: 180, difficulty: 3 },
      { id: "infectious-harrison-039", name: "هپاتیت ویروسی", minutes: 150, difficulty: 3 },
      { id: "infectious-harrison-040", name: "عفونت‌های تنفسی ویروسی شایع", minutes: 90, difficulty: 2 },
      { id: "infectious-harrison-041", name: "هرپس سیمپلکس", minutes: 90, difficulty: 2 },
      { id: "infectious-harrison-042", name: "آسپرژیلوز", minutes: 60, difficulty: 2 },
      { id: "infectious-harrison-043", name: "کاندیدیاز", minutes: 90, difficulty: 2 },
      { id: "infectious-harrison-044", name: "آمیبیاز", minutes: 60, difficulty: 2 },
      { id: "infectious-harrison-045", name: "مالاریا", minutes: 120, difficulty: 3 },
      { id: "infectious-harrison-046", name: "توکسوپلاسموز", minutes: 90, difficulty: 2 },
      { id: "infectious-harrison-047", name: "عفونت‌های رودهای تکیاخته‌ای و تریکومونیاز", minutes: 90, difficulty: 2 },
      { id: "infectious-harrison-048", name: "عفونت‌های کرمی روده‌ای", minutes: 90, difficulty: 2 },
      { id: "infectious-harrison-049", name: "عفونت‌های سستود", minutes: 60, difficulty: 2 },
      { id: "infectious-harrison-050", name: "گاستروانتریت ویروسی", minutes: 60, difficulty: 1 },
    ],
  },
  {
    id: "cardiology-harrison",
    name: "قلب (هاریسون)",
    aliases: ["قلب"],
    color: "#6366f1",
    topics: [
      { id: "cardiology-harrison-001", name: "نارسایی قلب", aliases: ["Heart Failure"], minutes: 120, difficulty: 3 },
      { id: "cardiology-harrison-002", name: "آریتمی‌ها", aliases: ["Arrhythmia"], minutes: 150, difficulty: 3 },
      { id: "cardiology-harrison-003", name: "سندرم کرونری حاد (ACS)", aliases: ["ACS"], minutes: 90, difficulty: 2 },
      { id: "cardiology-harrison-004", name: "رویکرد به بیمار قلبی و معاینه قلب", minutes: 90, difficulty: 2 },
      { id: "cardiology-harrison-005", name: "الکتروکاردیوگرافی و روش‌های تشخیصی قلب", minutes: 150, difficulty: 3 },
      { id: "cardiology-harrison-006", name: "بیماری ایسکمیک پایدار قلب", minutes: 120, difficulty: 2 },
      { id: "cardiology-harrison-007", name: "فیبریلاسیون و فلوتر دهلیزی", minutes: 120, difficulty: 3 },
      { id: "cardiology-harrison-008", name: "برادی‌آریتمی‌ها و اختلالات هدایت", minutes: 120, difficulty: 3 },
      { id: "cardiology-harrison-009", name: "تاکی‌کاردی بطنی و مرگ ناگهانی قلبی", minutes: 120, difficulty: 3 },
      { id: "cardiology-harrison-010", name: "کاردیومیوپاتی‌ها و میوکاردیت", minutes: 120, difficulty: 3 },
      { id: "cardiology-harrison-011", name: "بیماری‌های دریچه‌ای قلب", minutes: 150, difficulty: 3 },
      { id: "cardiology-harrison-012", name: "بیماری‌های پریکارد", minutes: 90, difficulty: 2 },
      { id: "cardiology-harrison-013", name: "بیماری‌های مادرزادی قلب در بزرگسالان", minutes: 120, difficulty: 3 },
      { id: "cardiology-harrison-014", name: "پرفشاری خون سیستمیک", minutes: 120, difficulty: 2 },
      { id: "cardiology-harrison-015", name: "بیماری‌های آئورت و عروق محیطی", minutes: 120, difficulty: 3 },
      { id: "cardiology-harrison-016", name: "شوک کاردیوژنیک و ادم ریوی", minutes: 90, difficulty: 3 },
      { id: "cardiology-harrison-017", name: "اختلالات چربی و پیشگیری قلبی‌عروقی", minutes: 90, difficulty: 2 },
      { id: "cardiology-harrison-018", name: "اندوکاردیت و تب روماتیسمی", minutes: 120, difficulty: 3 },
    ],
  },
  {
    id: "pharmacology",
    name: "فارماکولوژی",
    color: "#0ea5a4",
    topics: [
      { id: "pharmacology-001", name: "Autonomic", minutes: 80, difficulty: 2 },
      { id: "pharmacology-002", name: "Antibiotics", minutes: 100, difficulty: 2 },
      { id: "pharmacology-003", name: "CNS Drugs", minutes: 110, difficulty: 3 },
    ],
  },
  {
    id: "endocrinology-harrison",
    name: "غدد (هاریسون)",
    color: "#f97316",
    topics: [
      { id: "endocrinology-harrison-001", name: "رویکرد به اختلالات غدد درون‌ریز", minutes: 90, difficulty: 2 },
      { id: "endocrinology-harrison-002", name: "هیپوفیز قدامی و توده‌های ناحیه سلا", minutes: 120, difficulty: 3 },
      { id: "endocrinology-harrison-003", name: "اختلالات رشد و آکرومگالی", minutes: 90, difficulty: 2 },
      { id: "endocrinology-harrison-004", name: "دیابت بی‌مزه و اختلالات وازوپرسین", minutes: 90, difficulty: 3 },
      { id: "endocrinology-harrison-005", name: "رویکرد به بیماری‌های تیروئید", minutes: 90, difficulty: 2 },
      { id: "endocrinology-harrison-006", name: "کم‌کاری و پرکاری تیروئید", minutes: 150, difficulty: 3 },
      { id: "endocrinology-harrison-007", name: "ندول‌ها و سرطان تیروئید", minutes: 120, difficulty: 3 },
      { id: "endocrinology-harrison-008", name: "بیماری‌های قشر آدرنال", minutes: 150, difficulty: 3 },
      { id: "endocrinology-harrison-009", name: "فئوکروموسیتوم و بیماری‌های مدولای آدرنال", minutes: 90, difficulty: 3 },
      { id: "endocrinology-harrison-010", name: "دیابت ملیتوس؛ تشخیص و درمان", minutes: 180, difficulty: 3 },
      { id: "endocrinology-harrison-011", name: "عوارض حاد و مزمن دیابت", minutes: 150, difficulty: 3 },
      { id: "endocrinology-harrison-012", name: "هیپوگلیسمی", minutes: 90, difficulty: 2 },
      { id: "endocrinology-harrison-013", name: "اختلالات کلسیم و پاراتیروئید", minutes: 120, difficulty: 3 },
      { id: "endocrinology-harrison-014", name: "پوکی استخوان و بیماری‌های متابولیک استخوان", minutes: 120, difficulty: 2 },
      { id: "endocrinology-harrison-015", name: "چاقی و سندرم متابولیک", minutes: 90, difficulty: 2 },
      { id: "endocrinology-harrison-016", name: "اختلالات غدد تولیدمثل", minutes: 120, difficulty: 3 },
    ],
  },
  {
    id: "nephrology-harrison",
    name: "کلیه (هاریسون)",
    color: "#0ea5e9",
    topics: [
      { id: "nephrology-harrison-001", name: "رویکرد به بیمار کلیوی و آزمایش ادرار", minutes: 90, difficulty: 2 },
      { id: "nephrology-harrison-002", name: "اختلالات سدیم و تعادل آب", minutes: 120, difficulty: 3 },
      { id: "nephrology-harrison-003", name: "اختلالات پتاسیم", minutes: 90, difficulty: 3 },
      { id: "nephrology-harrison-004", name: "اختلالات اسید و باز", minutes: 150, difficulty: 3 },
      { id: "nephrology-harrison-005", name: "آسیب حاد کلیه", minutes: 150, difficulty: 3 },
      { id: "nephrology-harrison-006", name: "بیماری مزمن کلیه", minutes: 150, difficulty: 3 },
      { id: "nephrology-harrison-007", name: "دیالیز و پیوند کلیه", minutes: 120, difficulty: 3 },
      { id: "nephrology-harrison-008", name: "سندرم نفریتیک و گلومرولونفریت‌ها", minutes: 150, difficulty: 3 },
      { id: "nephrology-harrison-009", name: "سندرم نفروتیک", minutes: 120, difficulty: 3 },
      { id: "nephrology-harrison-010", name: "نفروپاتی دیابتی و بیماری‌های سیستمیک کلیه", minutes: 120, difficulty: 3 },
      { id: "nephrology-harrison-011", name: "بیماری‌های توبولی و بینابینی کلیه", minutes: 120, difficulty: 3 },
      { id: "nephrology-harrison-012", name: "بیماری‌های عروقی کلیه", minutes: 90, difficulty: 3 },
      { id: "nephrology-harrison-013", name: "بیماری‌های کیستیک و ارثی کلیه", minutes: 90, difficulty: 2 },
      { id: "nephrology-harrison-014", name: "سنگ‌های ادراری و نفروکلسی‌نوز", minutes: 90, difficulty: 2 },
      { id: "nephrology-harrison-015", name: "انسداد مجاری ادراری", minutes: 90, difficulty: 2 },
      { id: "nephrology-harrison-016", name: "عفونت ادراری و پیلونفریت", minutes: 90, difficulty: 2 },
    ],
  },
  {
    id: "rheumatology-harrison",
    name: "روماتولوژی (هاریسون)",
    color: "#8b5cf6",
    topics: [
      { id: "rheumatology-harrison-001", name: "رویکرد به درد مفصل و بیماری‌های روماتیسمی", minutes: 90, difficulty: 2 },
      { id: "rheumatology-harrison-002", name: "آزمایش‌های ایمنی و اتوآنتی‌بادی‌ها", minutes: 90, difficulty: 2 },
      { id: "rheumatology-harrison-003", name: "آرتریت روماتوئید", minutes: 150, difficulty: 3 },
      { id: "rheumatology-harrison-004", name: "لوپوس اریتماتوی سیستمیک", minutes: 150, difficulty: 3 },
      { id: "rheumatology-harrison-005", name: "سندرم آنتی‌فسفولیپید", minutes: 90, difficulty: 3 },
      { id: "rheumatology-harrison-006", name: "اسکلروز سیستمیک", minutes: 120, difficulty: 3 },
      { id: "rheumatology-harrison-007", name: "میوپاتی‌های التهابی", minutes: 90, difficulty: 3 },
      { id: "rheumatology-harrison-008", name: "سندرم شوگرن", minutes: 90, difficulty: 2 },
      { id: "rheumatology-harrison-009", name: "واسکولیت‌ها", minutes: 180, difficulty: 3 },
      { id: "rheumatology-harrison-010", name: "اسپوندیلوآرتریت‌ها", minutes: 120, difficulty: 3 },
      { id: "rheumatology-harrison-011", name: "نقرس و آرتریت‌های ناشی از کریستال", minutes: 120, difficulty: 2 },
      { id: "rheumatology-harrison-012", name: "استئوآرتریت", minutes: 90, difficulty: 2 },
      { id: "rheumatology-harrison-013", name: "آرتریت عفونی", minutes: 90, difficulty: 3 },
      { id: "rheumatology-harrison-014", name: "فیبرومیالژیا و اختلالات بافت نرم", minutes: 90, difficulty: 2 },
      { id: "rheumatology-harrison-015", name: "بیماری بهجت و بیماری‌های خودالتهابی", minutes: 120, difficulty: 3 },
      { id: "rheumatology-harrison-016", name: "سارکوئیدوز و آمیلوئیدوز", minutes: 120, difficulty: 3 },
    ],
  },
  {
    id: "hematology-harrison",
    name: "خون (هاریسون)",
    color: "#e11d48",
    topics: [
      { id: "hematology-harrison-001", name: "رویکرد به کم‌خونی و تفسیر شمارش سلول‌های خون", minutes: 120, difficulty: 2 },
      { id: "hematology-harrison-002", name: "کم‌خونی فقر آهن و کم‌خونی بیماری مزمن", minutes: 120, difficulty: 2 },
      { id: "hematology-harrison-003", name: "کم‌خونی مگالوبلاستیک", minutes: 90, difficulty: 2 },
      { id: "hematology-harrison-004", name: "کم‌خونی‌های همولیتیک", minutes: 120, difficulty: 3 },
      { id: "hematology-harrison-005", name: "هموگلوبینوپاتی‌ها و تالاسمی", minutes: 120, difficulty: 3 },
      { id: "hematology-harrison-006", name: "کم‌خونی آپلاستیک و نارسایی مغز استخوان", minutes: 90, difficulty: 3 },
      { id: "hematology-harrison-007", name: "اختلالات گرانولوسیت‌ها", minutes: 90, difficulty: 2 },
      { id: "hematology-harrison-008", name: "لوسمی‌های حاد", minutes: 150, difficulty: 3 },
      { id: "hematology-harrison-009", name: "لوسمی‌های مزمن", minutes: 120, difficulty: 3 },
      { id: "hematology-harrison-010", name: "لنفوم هوچکین و غیرهوچکین", minutes: 150, difficulty: 3 },
      { id: "hematology-harrison-011", name: "مولتیپل میلوما و اختلالات پلاسماسل", minutes: 120, difficulty: 3 },
      { id: "hematology-harrison-012", name: "نئوپلاسم‌های میلوپرولیفراتیو", minutes: 120, difficulty: 3 },
      { id: "hematology-harrison-013", name: "سندرم‌های میلودیسپلاستیک", minutes: 90, difficulty: 3 },
      { id: "hematology-harrison-014", name: "اختلالات پلاکت و ترومبوسیتوپنی", minutes: 120, difficulty: 3 },
      { id: "hematology-harrison-015", name: "اختلالات انعقاد و خونریزی", minutes: 150, difficulty: 3 },
      { id: "hematology-harrison-016", name: "ترومبوز و درمان ضدانعقادی", minutes: 120, difficulty: 3 },
      { id: "hematology-harrison-017", name: "طب انتقال خون", minutes: 90, difficulty: 2 },
      { id: "hematology-harrison-018", name: "پیوند سلول‌های بنیادی خون‌ساز", minutes: 90, difficulty: 3 },
    ],
  },
  {
    id: "gastroenterology-harrison",
    name: "گوارش (هاریسون)",
    color: "#d97706",
    topics: [
      { id: "gastroenterology-harrison-001", name: "رویکرد به علائم گوارشی و روش‌های تشخیصی", minutes: 90, difficulty: 2 },
      { id: "gastroenterology-harrison-002", name: "بیماری‌های مری و رفلاکس", minutes: 120, difficulty: 2 },
      { id: "gastroenterology-harrison-003", name: "زخم پپتیک و هلیکوباکتر پیلوری", minutes: 120, difficulty: 2 },
      { id: "gastroenterology-harrison-004", name: "خونریزی گوارشی", minutes: 150, difficulty: 3 },
      { id: "gastroenterology-harrison-005", name: "اسهال، سوءجذب و بیماری سلیاک", minutes: 150, difficulty: 3 },
      { id: "gastroenterology-harrison-006", name: "بیماری التهابی روده", minutes: 150, difficulty: 3 },
      { id: "gastroenterology-harrison-007", name: "سندرم روده تحریک‌پذیر و اختلالات عملکردی", minutes: 90, difficulty: 2 },
      { id: "gastroenterology-harrison-008", name: "بیماری‌های کولون و رکتوم", minutes: 120, difficulty: 2 },
      { id: "gastroenterology-harrison-009", name: "تومورهای دستگاه گوارش", minutes: 150, difficulty: 3 },
      { id: "gastroenterology-harrison-010", name: "رویکرد به بیماری کبد و تفسیر آزمایش‌های کبدی", minutes: 120, difficulty: 2 },
      { id: "gastroenterology-harrison-011", name: "هپاتیت‌های ویروسی", minutes: 150, difficulty: 3 },
      { id: "gastroenterology-harrison-012", name: "بیماری کبد چرب و کبد الکلی", minutes: 120, difficulty: 2 },
      { id: "gastroenterology-harrison-013", name: "بیماری‌های خودایمنی و متابولیک کبد", minutes: 120, difficulty: 3 },
      { id: "gastroenterology-harrison-014", name: "سیروز و عوارض پرفشاری پورت", minutes: 180, difficulty: 3 },
      { id: "gastroenterology-harrison-015", name: "نارسایی حاد کبد و پیوند کبد", minutes: 120, difficulty: 3 },
      { id: "gastroenterology-harrison-016", name: "بیماری‌های کیسه صفرا و مجاری صفراوی", minutes: 120, difficulty: 2 },
      { id: "gastroenterology-harrison-017", name: "پانکراتیت حاد و مزمن", minutes: 150, difficulty: 3 },
      { id: "gastroenterology-harrison-018", name: "تومورهای کبد، مجاری صفراوی و پانکراس", minutes: 120, difficulty: 3 },
    ],
  },
  {
    id: "pulmonology-harrison",
    name: "ریه (هاریسون)",
    color: "#14b8a6",
    topics: [
      { id: "pulmonology-harrison-001", name: "رویکرد به بیمار تنفسی و تست‌های عملکرد ریه", minutes: 120, difficulty: 2 },
      { id: "pulmonology-harrison-002", name: "آسم", minutes: 120, difficulty: 2 },
      { id: "pulmonology-harrison-003", name: "بیماری انسدادی مزمن ریه (COPD)", minutes: 120, difficulty: 3 },
      { id: "pulmonology-harrison-004", name: "برونشکتازی و فیبروز کیستیک", minutes: 90, difficulty: 2 },
      { id: "pulmonology-harrison-005", name: "پنومونی و آبسه ریه", minutes: 150, difficulty: 3 },
      { id: "pulmonology-harrison-006", name: "سل ریوی", minutes: 120, difficulty: 3 },
      { id: "pulmonology-harrison-007", name: "بیماری‌های بینابینی ریه", minutes: 150, difficulty: 3 },
      { id: "pulmonology-harrison-008", name: "بیماری‌های شغلی و محیطی ریه", minutes: 90, difficulty: 2 },
      { id: "pulmonology-harrison-009", name: "آمبولی ریه و ترومبوآمبولی وریدی", minutes: 150, difficulty: 3 },
      { id: "pulmonology-harrison-010", name: "پرفشاری خون ریوی", minutes: 120, difficulty: 3 },
      { id: "pulmonology-harrison-011", name: "بیماری‌های پلور و پنوموتوراکس", minutes: 120, difficulty: 2 },
      { id: "pulmonology-harrison-012", name: "بیماری‌های مدیاستن", minutes: 90, difficulty: 2 },
      { id: "pulmonology-harrison-013", name: "سرطان ریه", minutes: 150, difficulty: 3 },
      { id: "pulmonology-harrison-014", name: "اختلالات تنفسی حین خواب", minutes: 90, difficulty: 2 },
      { id: "pulmonology-harrison-015", name: "نارسایی تنفسی و سندرم دیسترس تنفسی حاد", minutes: 150, difficulty: 3 },
      { id: "pulmonology-harrison-016", name: "تهویه مکانیکی و اصول مراقبت تنفسی", minutes: 120, difficulty: 3 },
    ],
  },
  {
    id: "radiology-herring",
    name: "رادیولوژی (هرینگ)",
    color: "#3b82f6",
    topics: [
      { id: "radiology-herring-001", name: "اصول تصویربرداری و انتخاب روش مناسب", minutes: 90, difficulty: 1 },
      { id: "radiology-herring-002", name: "ایمنی پرتو و مواد حاجب", minutes: 60, difficulty: 1 },
      { id: "radiology-herring-003", name: "آناتومی طبیعی و رویکرد به رادیوگرافی قفسه سینه", minutes: 120, difficulty: 2 },
      { id: "radiology-herring-004", name: "بیماری‌های فضای هوایی و آتلکتازی", minutes: 120, difficulty: 2 },
      { id: "radiology-herring-005", name: "افیوژن پلور و پنوموتوراکس در تصویربرداری", minutes: 90, difficulty: 2 },
      { id: "radiology-herring-006", name: "قلب و عروق در رادیوگرافی قفسه سینه", minutes: 90, difficulty: 2 },
      { id: "radiology-herring-007", name: "ندول‌ها و توده‌های ریه و مدیاستن", minutes: 120, difficulty: 3 },
      { id: "radiology-herring-008", name: "ابزارها، لوله‌ها و کاتترها در تصاویر", minutes: 90, difficulty: 2 },
      { id: "radiology-herring-009", name: "اصول تصویربرداری شکم و لگن", minutes: 90, difficulty: 2 },
      { id: "radiology-herring-010", name: "انسداد روده و هوای آزاد شکمی", minutes: 120, difficulty: 3 },
      { id: "radiology-herring-011", name: "تصویربرداری کبد، صفرا و پانکراس", minutes: 120, difficulty: 2 },
      { id: "radiology-herring-012", name: "تصویربرداری دستگاه ادراری", minutes: 90, difficulty: 2 },
      { id: "radiology-herring-013", name: "شکستگی‌ها و دررفتگی‌ها", minutes: 150, difficulty: 3 },
      { id: "radiology-herring-014", name: "بیماری‌های مفاصل و ضایعات استخوانی", minutes: 120, difficulty: 2 },
      { id: "radiology-herring-015", name: "تصویربرداری مغز؛ خونریزی و سکته", minutes: 150, difficulty: 3 },
      { id: "radiology-herring-016", name: "تصویربرداری ستون فقرات", minutes: 90, difficulty: 2 },
      { id: "radiology-herring-017", name: "اصول سونوگرافی، سی‌تی و ام‌آر‌آی", minutes: 120, difficulty: 2 },
      { id: "radiology-herring-018", name: "مرور تصویربرداری اورژانس و تروما", minutes: 120, difficulty: 3 },
    ],
  },
];
